### ISSUE TITLE
Water bond angle not correct

### ISSUE THREAD

**Issue by althea-hansel** [forlilab/Meeko#100]
I am giving meeko a receptor to prepare with water oxygen positions only, allowing it to add hydrogens to the waters. The resulting bond angle for the waters in the PDBQT is 109.5°, not 104.5°

**Comment by diogomart** [comment]
RDKit adds the hydrogens, and it uses a minimal set of rules to specify the geometry. I think that we need to minimize the hydrogens with a force field like OpenFF or Espaloma.

That's probably not a big deal for the calculation, in view of the quality of the partial charges, lack of polarization, and modern water models using angles closer to 109 than to 105 deg (OPC3 and TIP3P-FB) https://www.ncbi.nlm.nih.gov/pmc/articles/PMC4991989/table/t2/?report=objectonly

**Comment by althea-hansel** [comment]
So, leave it as is?

**Comment by diogomart** [comment]
yes
