### ISSUE TITLE
rigid ligand docking

### ISSUE THREAD

**Issue by alfredoq** [forlilab/Meeko#102]
Dear Meeko developers,

while preparing a molecule .pdbqt is there a way to indicate that all rotatable bonds should be kept rigid?

many thanks in advance,

Alfredo

**Comment by diogomart** [comment]
Dear Alfredo,

Yes with
```
-r "[*][*]" -b 1 2
```
These options are the short version of
```
  -r SMARTS, --rigidify_bonds_smarts SMARTS
                        SMARTS patterns to rigidify bonds
  -b i j [i j ...], --rigidify_bonds_indices i j [i j ...]
                        indices of two atoms (in the SMARTS) that define a bond (start at 1)
```

**Comment by alfredoq** [comment]
Thank you Diogo for the prompt reply,

and in case of using Meeko through the Python api, this should be indicated as a parameter? (which one?)

Thank you again!

**Comment by diogomart** [comment]
You are welcome.

It's `rigidify_bonds_smarts` and `rigidify_bonds_indices`. For example:
https://github.com/forlilab/Meeko/?tab=readme-ov-file#possibly-useful-configurations-of-moleculepreparation

**Comment by alfredoq** [comment]
great! I will try it,

thanks
