### ISSUE TITLE
Ligand preparation for covalent docking with mk_prepare_ligand.py

### ISSUE THREAD

**Issue by lovenicole** [forlilab/Meeko#103]
Hi, I want to prepare ligand for covalent docking. 

However, when I open the help message with the "mk_prepare_ligand.py --help" command, 
the message of the Covalent docking part is like below. 
![image](https://github.com/forlilab/Meeko/assets/74394164/c885e8ad-d35d-4c15-b8e9-c83844098435)

I tried preparing one ligand with the command below. 
`mk_prepare_ligand.py -i $id.mol2 -o $id.pdbqt --receptor 8x6r_A_1.pdb --rec_residue "A:CYS:12" --tether_smarts "CCSCC(=O)N" --tether_smarts_indices 1 2`

But I got the error. 
> Covalent docking requires Prody which is not available

I installed Meeko 0.5.0 with `pip install meeko`.

How can I solve it?

**Comment by rwxayheee** [comment]
Hi @lovenicole 
Please try `pip install prody` to install prody (2.4.1 at the moment)

**Comment by lovenicole** [comment]
> Hi @lovenicole Please try `pip install prody` to install prody (2.4.1 at the moment)

Thank you very much! The problem is solved.
