### ISSUE TITLE
mk_prepare_ligand.py rdkit.six autodockVina

### ISSUE THREAD

**Issue by HeheHahaHoHoHo** [forlilab/Meeko#112]
Hi all, 
V. amateur-ish question but if someone could help out, it seems rdkit.six no longer exists. When i execute mk_prepare_ligand.py, it states  no module named rdkit.six. I can see that a new version of rdkit_mol_create.py has been created to replace rdkit.six StringIO with os. I was wondering how can i go about getting that version and if i should replace the whole meeko package? 

Also, if anyone is curious where my problem is stemming from, im currently following https://autodock-vina.readthedocs.io/en/latest/introduction.html but the rdkit.six problem seems to be new. 

Appreciate any help.
Thanks

**Comment by rwxayheee** [comment]
`I was wondering how can i go about getting that version and if i should replace the whole meeko package?`
I replied to your original post in ccsb-scripps/AutoDock-Vina/issues/306. Installing the most recent version from this repository should work. But alternatively, downgrading RDKit might be another option. Let us know if there are any further issues!

**Comment by HeheHahaHoHoHo** [comment]
@rwxayheee Hey thanks a lot of the reply and apologises to get back late to this. 

Apologises for the shortcoming but how exactly do i "install the most recent version from this repository". I basically git clone https://github.com/forlilab/Meeko which leads me to the releases script... do i have to manually download other versions and put it into my database? 

I was hoping not to downgrade RDKIT for now but lets see how it goes....

Thanks alot for any help

**Comment by rwxayheee** [comment]
Hi @HeheHahaHoHoHo 
Sorry for my confusion. According to #96 this issue was addressed in ed395cc. However, it seems like the change hasn't been made to the release branch yet. So, you might need to get and install from the develop branch: 
`git clone -b develop https://github.com/forlilab/Meeko`

the [README](https://github.com/forlilab/Meeko?tab=readme-ov-file#installation-from-source) might be a bit misleading since develop is currently not the default branch

**Comment by HeheHahaHoHoHo** [comment]
Hey @rwxayheee, 
                           Thanks a lot for the help. I didnt even know you could git clone different branches (I was looking for a way to do this so thanks a lot in helping this github newbie). I have installed the develop script of meeko folder into the site-packages and it seems to be working fine for now.... 

Thanks a lot :)
