### ISSUE TITLE
PDBQT parsing for receptors removes charge sign

### ISSUE THREAD

**Issue by bradakta** [forlilab/Meeko#116]
As the title says. The _read_receptor_pdbqt_string() function excludes the field containing the sign of partial charges so that all partial charges are read as positive. It would seem that `partial_charges = float(line[71:77].strip())` should instead be `partial_charges = float(line[70:77].strip())`.

I'm guessing this never has a tangible effect on docking, only the python data structure?

**Comment by rwxayheee** [comment]
Yes, this used to be [70:76] (with a size of 6) in AutoDock4

**Comment by diogomart** [comment]
It has been fixed in 403907eb0796b2e6c257d969c9309cbd1fcd6d7b but I just realized it also needs to be fixed in https://github.com/forlilab/Meeko/blob/71ce3e0900b839953561618357a921ec18f16101/meeko/molecule_pdbqt.py#L132

**Comment by diogomart** [comment]
@bradakta thanks for reporting this. It does not affect docking, these data structures are used only to process docking results, not to create input for docking.
