### ISSUE TITLE
pH Specification for mk_prepare_ligand.py as described by AutoDockVina? 

### ISSUE THREAD

**Issue by DKchemistry** [forlilab/Meeko#12]
Dear Meeko Team, 

Meeko is featured in the AutoDockVina documentation (https://autodock-vina.readthedocs.io/_/downloads/en/latest/pdf/) and in their tutorial, utilizes the following code: 

mk_prepare_ligand.py -i 1iep_ligand.sdf -o 1iep_ligand.pdbqt --pH 7.4

However, I get an unrecognized arugment error for --ph 7.4 

Looking through the github via ctrl+f, I don't see a mention of pH. 

Has this argument been replaced with a different argument? 

Thank you

**Comment by diogomart** [comment]
Hello,

The `--pH` option was removed since version 0.3.0. Updated Vina docs right now: https://github.com/ccsb-scripps/AutoDock-Vina/commit/75f87a4b4fa05ad7f29e47190076bf0615ed1e34

See https://github.com/forlilab/Meeko/issues/11 for more info.

Best regards
