### ISSUE TITLE
Non-covalent complex docking to a receptor using AutoDock suite of programs

### ISSUE THREAD

**Issue by Hariharan-Annadurai-bit** [forlilab/Meeko#126]
Hi,
Is it possible to dock a non-covalently bound complex(A-B) as ligand to a receptor in AutoDock suite of programs?
thanks,
Hari

**Comment by diogomart** [comment]
Hello,

If A and B are allowed to move independently, yes, in Vina, as simultaneous docking of separate ligands.

If the idea is to keep the relative positions of A and B fixed, it would require a lot of manipulation of the input PDBQT file, We don't have an automated way to do that. It would require a way to define which atoms of A and B are fixed relative to each other, and which parts are allowed to move.
