### ISSUE TITLE
LinkerRDKitChorizo cannot process PRO residue

### ISSUE THREAD

**Issue by HaoLan-compchem** [forlilab/Meeko#136]
I tried to use mk_prepare_receptor.py for preparing protein grid before ligand docking.

Here is an error given by meeko:

   "C:PRO:357": "C:PRO:357"
}
Traceback (most recent call last):
  File "/data/home/hlan/.conda/envs/bd_env/bin/mk_prepare_receptor.py", line 332, in <module>
    chorizo = LinkedRDKitChorizo(pdb_string, mutate_res_dict=mutate_res_dict, termini=termini, deleted_residues=del_res, allow_bad_res=args.allow_bad_res, skip_auto_disulfide=args.skip_auto_disulfide)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/home/hlan/.conda/envs/bd_env/lib/python3.11/site-packages/meeko/linked_rdkit_chorizo.py", line 260, in __init__
    raise RuntimeError(msg)
RuntimeError: The following residues could not be processed:
Resname: PRO:
C:231 C:357

Here is one PRO residue data (with protons) in my PDB file:

ATOM  11226  N   PRO C 357     -43.712 -25.058  11.337  1.00  0.00      A    N
ATOM  11227  CA  PRO C 357     -43.210 -23.926  12.134  1.00  0.00      A    C
ATOM  11228  C   PRO C 357     -42.343 -22.913  11.363  1.00  0.00      A    C
ATOM  11229  O   PRO C 357     -41.303 -23.272  10.801  1.00  0.00      A    O
ATOM  11230  CB  PRO C 357     -42.407 -24.544  13.277  1.00  0.00      A    C
ATOM  11231  CG  PRO C 357     -43.095 -25.897  13.491  1.00  0.00      A    C
ATOM  11232  CD  PRO C 357     -43.478 -26.300  12.065  1.00  0.00      A    C
ATOM  11233  HA  PRO C 357     -44.062 -23.384  12.570  1.00  0.00      A    H
ATOM  11234 1HB  PRO C 357     -42.433 -23.933  14.179  1.00  0.00      A    H
ATOM  11235 2HB  PRO C 357     -42.842 -25.515  13.560  1.00  0.00      A    H
ATOM  11236 1HG  PRO C 357     -43.989 -25.757  14.087  1.00  0.00      A    H
ATOM  11237 2HG  PRO C 357     -43.412 -26.319  12.525  1.00  0.00      A    H
ATOM  11238 1HD  PRO C 357     -44.370 -26.922  12.108  1.00  0.00      A    H
ATOM  11239 2HD  PRO C 357     -43.653 -25.396  11.463  1.00  0.00      A    H

My conda environment version of meeko and rdkit:
 
meeko 0.6.0a3  pypi_0 pypi
rdkit    2023.9.5 pypi_0 pypi

I have also tried to downgrade meeko to 0.5.0 which is even worse (process much less residues excluding HIS...)

So I am wondering if it could an issue of the version of rdkit Chem.MolFromPDBBlock module which is called in the LinkerRDKitChorizo.py script? Is there a way to process the proline residue with protons in above format?

Thank you very much.

**Comment by diogomart** [comment]
Hi,

the hydrogens are messed up, v0.6.0a3 should work if the hydrogens are fixed or removed
![pro357](https://github.com/forlilab/Meeko/assets/1564797/7e153d2e-33e8-40f7-beee-d9161a9a3172)
