### ISSUE TITLE
Python Packaging Issues

### ISSUE THREAD

**Issue by xavierholt** [forlilab/Meeko#139]
I'm trying to install Meeko in a Python 3.12 virtual environment on a clean Ubuntu 24.04 system.  I've run into a couple problems, all related to package dependencies:

- Running `pip install meeko` installs Meeko 0.5.0, but this uses `from rdkit.six import StringIO` and that's incompatible with the latest version of RDKit (2024.3.3).
- Meeko 0.5.1 contains the fix for this, but it won't install via `pip` because it's listed as incompatible with Python 3.12 in `setup.py`.
- There are a few other packages that Meeko imports but doesn't list as dependencies, so it'll crash when you run it without these installed.

I was able to get things working by cloning the repo, editing `setup.py` and installing from source, but it would be nice if things were easier via `pip`.  I think the following would take care of it:

- Remove the Python < 3.12 restriction in `setup.py`.
- Add `pandas`, `rdkit`, and `scipy` as package dependencies.

It looks like the Python version restriction was added in https://github.com/forlilab/Meeko/commit/03d4168a72cb0d52043852ae388f025e5461e84c to work around ProDy restrictions, so I have no idea how feasible removing it would be...  Alternatively, you could pin RDKit to version 2023.9.6 (or earlier), which was the last to include the `rdkit.six` submodule.

**Comment by diogomart** [comment]
Thank you for your comment. We have a tough decision to make for meeko v0.6. Our current plan is to require prody (to parse mmcif mostly). But prody doesn't work on 3.12. Removing the <3.12 restriction worked for v0.5 because prody is optional in meeko v0.5 (it's used only for tethered docking). For meeko v0.6 we have to choose between 3.12 or prody, can't have both unfortunately.

**Comment by diogomart** [comment]
Could Python 3.11 work for you?

**Comment by xavierholt** [comment]
It looks like Python 3.12 is the only officially supported Python version on Ubuntu 24.04.  You can install other versions via unofficial APT repos (a quick Google turned up [deadsnakes](https://launchpad.net/%7Edeadsnakes/+archive/ubuntu/ppa)), but in my case I'm running on AWS, so it's easier to switch to an Ubuntu 22.04 machine than to deal with non-standard packages.  This'll be more of a problem for people running on local machines.

Anyway, it sounds like the underlying problem is ProDy, not Meeko.  I don't see any tickets regarding Python 3.12 on their GitHub page, so I'll open one and ask.

**Comment by diogomart** [comment]
Micromamba has been working well for me, where "working well" is in light of the complexity of python dependency networks. For example, this should work out of the box and result in a python 3.11 installation:
```
micromamba create -n myenv
micromamba activate  myenv
micromamba install meeko
```

**Comment by xavierholt** [comment]
Thanks!  Using `micromamba` seems to be easy enough for now.  I'm a little nervous 'cause it installed Python 3.11 without me specifying that anywhere, but I can confirm it works on Ubuntu 24.04.

In the meantime, I opened https://github.com/prody/ProDy/issues/1915 asking about Python 3.12 support for ProDy.

**Comment by diogomart** [comment]
It installed 3.11 because meeko's conda recipe restricts to <3.12. You can have multiple environments with different python versions, or package versions, and pin the python version with `micromamba install python=3.12`. You can also pip install inside these environments. There's a good chance things will get messed up, eventually, but navigating Python dependencies is nicer with micromamba than without it.

**Comment by David-OConnor** [comment]
Notes:

- Meeko itself works if you download the repo, change `setup.py` to support new versions.
- mmCIF ingests requires Prody. Prody (outside the scope of this repo with different stakeholders), only supports very old Python versions.

Not sure how to proceed. Maybe package as an executable using PyO3 or something? Relying on an external interpreter seems to be a trap.

**Comment by rwxayheee** [comment]
Hi @David-OConnor 

Another feature that currently relies on ProDy is covalent docking preparation. See my comments in a recent conversation: 

https://github.com/forlilab/Meeko/pull/318#issuecomment-2669732854

If you use Meeko only for protein structure preparation then this wont be a problem. 

To become entirely independent from ProDy and support 3.13 we got some more refactoring to do. At the moment the recommended Python version for Meeko is 3.10.

**Comment by David-OConnor** [comment]
I love Python as a language, but its dependency-management and software-distribution has room for improvement.

**Comment by rwxayheee** [comment]
Hi @David-OConnor 

Out of curiosity, will you be using Meeko as a docking (PDBQT) preparation tool, or just for protein preparation? Unless you’re developing with Meeko as a module in your meta package, you can have a python310 environment for Meeko (more for ProDy, actually) and run our command line scripts or your own Meeko python script in that certain environment/interpreter.  

Is there a specific Python package you will be using with Meeko, that requires a newer Python? We would like to know for information purposes. Thanks!

**Comment by David-OConnor** [comment]
Thank you for the  information and tip on a dedicated Python 3.10 interpreter. I'll be using it for docking; both protein and ligand preparation.

I think the most straightforward solution there would be, as I don't use 3.10 for anything else, installing Python 3.10, and using that for Meeko. I think the more general solution is what you said: Set up a virtual environment.

There is a subtlety: Meeko is intended as both A: A python library. B: A CLI script (We can pretend it's a CLI application). I think for A, the solution you proposed would work *if there are no other picky dependencies in the application calling the lib*, and if no >3.10 features are desired. For B, the easiest solution (From the user's perspective), is to use something like [PyOxidizer](https://gregoryszorc.com/docs/pyoxidizer/main/) to distribute it as a binary.

**Comment by diogomart** [comment]
One solution would be to include Prody's mmCIF parser in Meeko instead of using it as an external dependency. I think we can redistribute Prody's MIT source as part of Meeko which is LGPLv2.

**Comment by David-OConnor** [comment]
I like that idea.
