### ISSUE TITLE
RuntimeError: Can't handle 3 explicit H for each heavy atomin noH mol.

### ISSUE THREAD

**Issue by davidyanglee** [forlilab/Meeko#14]
In a batch mode for mk_prepare_ligand, how may one solve the following problem in batch mode?

RuntimeError: Can't handle 3 explicit H for each heavy atomin noH mol.
Was expecting only imines [H]N=

Thank you.
David

**Comment by diogomart** [comment]
Can you share the molecule that produces the error?

We'll need to raise a warning instead of an error, at least in batch mode. Meanwhile one way to fix it is to remove the problematic molecule. Sorry about that... 

Thank you

**Comment by diogomart** [comment]
Probably fixed in #39. Feel free to open a new issue, or re-open this one if necessary.
