### ISSUE TITLE
Converting PQBQT to multiple RDKIT molecules

### ISSUE THREAD

**Issue by QY0831** [forlilab/Meeko#140]
Hi dev,
Is there a way to convert all poses to RDKIT molecules?
```
>>> op = 'vina_out.pdbqt'
>>> pdbqt_mol = PDBQTMolecule.from_file(op, skip_typing=True)
>>> rdkitmol_list = RDKitMolCreate.from_pdbqt_mol(pdbqt_mol)
>>> rdkitmol_list
[<rdkit.Chem.rdchem.Mol object at 0x7f23c13d2970>]
>>> pdbqt_mol
<Molecule named forcefield_5241_out containing 2 poses of 35 atoms>
```
I set 'num_modes=2' in vina, so there are two poses in the PDBQT file.
I know that it only return one rdkit mol if only one ligand was docked, but I want to get all the poses, Is there a way to do that? Thanks

**Comment by diogomart** [comment]
Hello,
The poses are stored as conformers in the molecule. If there are flexible sidechains or multiple simultaneous ligands, the returned list will have multiple rdkit mols.

**Comment by QY0831** [comment]
Successfully converted into multiple objects, thanks!
```
>>> print([x.GetId() for x in rdmol.GetConformers()])
[0, 1]
>>> m1 = Chem.Mol(rdmol, confId=0)
>>> m2 = Chem.Mol(rdmol, confId=1)
```
