### ISSUE TITLE
ERROR : import meeko rdkit.six module mot found

### ISSUE THREAD

**Issue by layal-khayal** [forlilab/Meeko#141]
` 
from meeko import MoleculePreparation
from meeko import PDBQTWriterLegacy
{
	"name": "ModuleNotFoundError",
	"message": "No module named 'rdkit.six'",
	"stack": "---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
Cell In[22], line 1
----> 1 from meeko import MoleculePreparation
      2 from meeko import PDBQTWriterLegacy

File ~/miniconda3/envs/Docking/lib/python3.12/site-packages/meeko/__init__.py:32
     30 from .receptor_pdbqt import PDBQTReceptor
     31 from .molecule_pdbqt import PDBQTMolecule
---> 32 from .rdkit_mol_create import RDKitMolCreate
     33 from .reactive import reactive_typer
     34 from .reactive import get_reactive_config

File ~/miniconda3/envs/Docking/lib/python3.12/site-packages/meeko/rdkit_mol_create.py:11
      9 from rdkit.Geometry import Point3D
     10 from rdkit.Chem import AllChem
---> 11 from rdkit.six import StringIO
     12 import json
     13 import os

ModuleNotFoundError: No module named 'rdkit.six'"
}
`

Although rdkit is correctly omported and it worked perfectly calling other modules 

`from rdkit import six

{
	"name": "ImportError",
	"message": "cannot import name 'six' from 'rdkit' (/home/layal/miniconda3/envs/Docking/lib/python3.12/site-packages/rdkit/__init__.py)",
	"stack": "---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
Cell In[23], line 1
----> 1 from rdkit import six

ImportError: cannot import name 'six' from 'rdkit' (/home/layal/miniconda3/envs/Docking/lib/python3.12/site-packages/rdkit/__init__.py)"
}
`

**Comment by diogomart** [comment]
Few options:

- meeko v0.5.1
- meeko from develop branch (local install with git clone, cd Meeko, git checkout develop, pip install .)
- downgrade rdkit to <2024
