### ISSUE TITLE
remove openbabel for v0.6

### ISSUE THREAD

**Issue by diogomart** [forlilab/Meeko#145]
The only feature that might still be in use with the openbabel code path is `mk_export.py --original_input` (https://github.com/forlilab/Meeko/issues/23). It's probably no longer in use because it has been 2 years since the atom indices required for `--original_input` aren't added by default with `mk_prepare_ligand.py`. It can be re-implemented with the RDKit code path if the need arises.

**Comment by rwxayheee** [comment]
This was completed in [50dfda0](https://github.com/forlilab/Meeko/pull/157/commits/50dfda0c991b7ba83cbcf5ca5b1801a2c818ecfb) + [5f2f1bd](https://github.com/forlilab/Meeko/pull/157/commits/5f2f1bdfbf662b4c21ff89104bd0eb73bff0044a). 
At present in the develop branch, the option `--original_input` is removed. Please feel free to reopen if it needs to be re-implemented
