### ISSUE TITLE
The ligand prepared by Meeko for docking using AutoDock-GPU has unusual atoms

### ISSUE THREAD

**Issue by aprijal99** [forlilab/Meeko#158]
I want to dock a compound from PubChem with ID [11481776](https://pubchem.ncbi.nlm.nih.gov/compound/11481776) using AutoDock GPU, but encountered an error when generating grid maps using Autogrid4. It said "ERROR:  unknown ligand atom type CG0". Then I looked into the compound pdbqt file and found unusual atoms "G"

The pdbqt file of the compound is ok when it was generated by "prepare_ligand" program from ADFR

**Comment by aprijal99** [comment]
![Screenshot 2024-09-01 070944](https://github.com/user-attachments/assets/7a524879-188f-4339-9d52-8c84011f4f3b)

**Comment by rwxayheee** [comment]
Hi @aprijal99 
These are atom types used for macrocycle sampling (https://autodock-vina.readthedocs.io/en/latest/docking_macrocycle.html) which is supported by Vina 1.2 and AutoDock GPU, but maybe not by ADFR. 
This function is implemented to sample alternate conformations of (by default, 7 and above)-membered rings in docking calculation. The method was first described in this paper: 
https://pubs.acs.org/doi/abs/10.1021/ci700036j

If you use ADFR as the docking engine, in ligand preparation you can turn off the macrocycle atom typing using the **--rigid_macrocycles** option. You can find some examples from the README of this project when you scroll to here: 
https://github.com/forlilab/Meeko?tab=readme-ov-file#possibly-useful-configurations-of-moleculepreparation

Feel free to reopen the issue if you need any further help
