### ISSUE TITLE
Raise helpful error message when reactive smarts doesn't match

### ISSUE THREAD

**Issue by diogomart** [forlilab/Meeko#161]
Currently we get the following, which is does not help the user figure out the problem. Thanks @althea-hansel for finding this one 
```python
meeko/preparation.py", line 577, in prepare

    self.deprecated_setup_access = setups[0]

IndexError: list index out of range
```

**Comment by rwxayheee** [comment]
This was addressed by [82c5702](https://github.com/forlilab/Meeko/pull/157/commits/82c570208e6a9bb1ca19c21ab7c605a33cd1ab9f)
