### ISSUE TITLE
mk_prepare_receptor for reactive docking isn't working with --macromol (Prody parser) 

### ISSUE THREAD

**Issue by rwxayheee** [forlilab/Meeko#168]
The origin of this issue is

https://github.com/forlilab/Meeko/blob/5f29de0c7e8f0193c0673db1785b38196c24708b/meeko/reactive.py#L120

only works when RDKit's PDB parser is used. Currently, the easy walkaround is to use --pdb (RDKit parser). Happy to provide a simple fix (but can also wait until other major changes are made, if Prody is going to be optional in the near future!

**Comment by diogomart** [comment]
Making prody optional is a small change, it simply consists of wrapping the imports inside try/except blocks:
https://github.com/forlilab/Meeko/commit/b7cc4dca7a5e4897492ba9fa94b1c7eaea974307

**Comment by rwxayheee** [comment]
Hi @diogomart 
Covalent docking (https://github.com/forlilab/Meeko/blob/5f29de0c7e8f0193c0673db1785b38196c24708b/meeko/covalentbuilder.py#L4) depends on prody. Would you be interested in making it optional? 
If you assign the work to me I can work from https://github.com/forlilab/Meeko/commit/b7cc4dca7a5e4897492ba9fa94b1c7eaea974307. But if you think it's not important, I can provide a simple fix (or guard) to this issue

**Comment by diogomart** [comment]
Just to keep the record here of what we talked about yesterday: prody has always been optional for covalent docking.

**Comment by rwxayheee** [comment]
Are you planning to merge it [optional_prody](https://github.com/forlilab/Meeko/tree/optional_prody)
in the near future? 

~~I don't know how to reproduce the original issue now.~~ 

Input files:
[1d3g_input.zip](https://github.com/user-attachments/files/17137441/1d3g_input.zip)

Input commands: 
```
mk_prepare_receptor.py --macromol 1d3g_input/1d3g_receptor.pdb --allow_bad_res \
--box_enveloping 1d3g_input/1d3g_FMN.pdb --padding 2 \
--reactive_flexres "A:100,255" \
--flexres "A:145,356,100" \
--reactive_name "LYS:CG" \
--reactive_name_specific "A:255=NZ" \
--output_filename 1d3g_output_5
```

Output:
```
Traceback (most recent call last):
  File "/Users/amyhe/micromamba/envs/mk_dev/bin/mk_prepare_receptor.py", line 7, in <module>
    exec(compile(f.read(), __file__, 'exec'))
  File "/Users/amyhe/Desktop/0_forks/Meeko/scripts/mk_prepare_receptor.py", line 471, in <module>
    reactive_atomi = atom_name_to_molsetup_index(
  File "/Users/amyhe/Desktop/0_forks/Meeko/meeko/reactive.py", line 120, in atom_name_to_molsetup_index
    name = atom.GetPDBResidueInfo().GetName().strip()
AttributeError: 'NoneType' object has no attribute 'GetName'
```

**Comment by rwxayheee** [comment]
I will suggest an alternate fix a little later. Thanks @diogomart for looking into this
