### ISSUE TITLE
Not reading molecule names from SDF

### ISSUE THREAD

**Issue by althea-hansel** [forlilab/Meeko#170]
**Commit:** 5f29de0
**Expected behavior:** Write PDBQTs with names matching those read from the input SDF file
**Observed behavior:** all PDBQTs written with input SDF as basename and `_again{n}` suffix

**Comment by diogomart** [comment]
It's to disambiguate repeated names. Does that fully explain the behavior you see?

**Comment by althea-hansel** [comment]
No, I mean that _every_ ligand is written like that

**Comment by diogomart** [comment]
can you post an example sdf?

**Comment by althea-hansel** [comment]
It looks like the change originated here 5f2f1bdfbf662b4c21ff89104bd0eb73bff0044a

It is this line https://github.com/forlilab/Meeko/blob/5f29de0c7e8f0193c0673db1785b38196c24708b/scripts/mk_prepare_ligand.py#L612

Reverting back to `output(pdbqt_string, name, (suffix,))` seems to solve my issue

**Comment by rwxayheee** [comment]
Hello @althea-hansel 

Yes this is because of https://github.com/forlilab/Meeko/commit/5f2f1bdfbf662b4c21ff89104bd0eb73bff0044a

`output(pdbqt_string, name, (suffix,))`

Reverting to this might not work for reactive docking. 

Could you post your SDF file?

**Comment by rwxayheee** [comment]
If you have an SDF of many different molecules, reverting this line to the original one is the quick fix. It assumes SDF has valid name properties. 

We can revert it for the time being, but it will not work for reactive docking (when len(molsetup) becomes > 1 during ligand preparation). I can fix reactive docking in a different way then. 

There were many changes introduced by the multimol commit. Would any of you be ok with rewriting it (and with some testing of different types of docking)?

**Comment by althea-hansel** [comment]
Ok, I made a PR with the fix: https://github.com/forlilab/Meeko/pull/171

**Comment by rwxayheee** [comment]
I merged #171 to develop. Thanks again for reporting and the fix!
