### ISSUE TITLE
name 'rdkit_molecule_3D_with_Hs' is not defined

### ISSUE THREAD

**Issue by ehdhssh** [forlilab/Meeko#190]
Hello, I have installed all the packages, but when I run "python mk_prepare_ligand.py -i GC.sdf -o GC.pdbqt," I encounter the error "File 'mk_prepare_ligand.py', line 5, in <module> mol_setups = preparator.prepare(rdkit_molecule_3D_with_Hs) NameError: name 'rdkit_molecule_3D_with_Hs' is not defined." How can I resolve this? Thank you!

**Comment by diogomart** [comment]
Hello, looks like you copied the Python script example into a file called `mk_prepare_ligand.py`. That's an example for Python scripting, but you still have to write your own script based on that.

You could just use the `mk_prepare_ligand.py` that is readily available when you install Meeko.
