### ISSUE TITLE
Issue with Atom Types in Ligand File for AutoDock Vina (GPU)-2.1

### ISSUE THREAD

**Issue by aashuph16221** [forlilab/Meeko#212]
Hello,

I am working on a ligand library that I generated using Meeko, and I am using AutoDock Vina (GPU version) for docking. However, I am encountering an issue with some of the ligands in the PDBQT files.

In particular, the ligands contain the following non-standard atom types:
CG1,G1,G0,G
When I run AutoDock Vina, it raises errors about these atom types and cancels the job. Here is an  ligand files for reference:

REMARK SMILES Cc1cc(S(=O)(=O)N2C[C@@H]3COC[C@H](C2)[N@H+](C)C3)c(C)s1
REMARK SMILES IDX 18 1 10 2 9 4 8 5 5 6 6 7 7 8 4 9 19 10 3 11 21 12 20 13
REMARK SMILES IDX 2 14 1 15 15 16 16 18 17 19 14 21 13 23 12 24 11 25
REMARK H PARENT 16 20
REMARK Flexibility Score: 160.00
ROOT
ATOM      1  C   UNL     1      -2.300   0.935  -0.798  1.00  0.00     0.269 C
ENDROOT
BRANCH   1   2
ATOM      2  C   UNL     1      -2.092   0.900   0.733  1.00  0.00     0.085 CG1
ATOM      3  G   UNL     1      -3.084  -0.037   1.465  1.00  0.00     0.000 G1
BRANCH   2   4
ATOM      4  C   UNL     1      -0.607   0.657   1.100  1.00  0.00     0.114 C
BRANCH   4   5
ATOM      5  N   UNL     1      -0.175  -0.745   0.932  1.00  0.00    -0.191 NA
BRANCH   5   6
ATOM      6  S   UNL     1       1.503  -0.899   1.402  1.00  0.00     0.244 S
ATOM      7  O   UNL     1       1.920  -2.341   1.318  1.00  0.00    -0.207 OA
ATOM      8  O   UNL     1       1.657  -0.461   2.832  1.00  0.00    -0.207 OA
BRANCH   6   9
ATOM      9  C   UNL     1       2.560   0.098   0.394  1.00  0.00     0.096 A
ATOM     10  C   UNL     1       3.243  -0.342  -0.745  1.00  0.00     0.022 A
ATOM     11  C   UNL     1       2.784   1.454   0.678  1.00  0.00     0.037 A
ATOM     12  S   UNL     1       4.111   0.953  -1.381  1.00  0.00    -0.145 S
ATOM     13  C   UNL     1       3.282  -1.727  -1.307  1.00  0.00     0.058 C
ATOM     14  C   UNL     1       3.641   2.073  -0.222  1.00  0.00     0.003 A
ATOM     15  C   UNL     1       4.005   3.520  -0.230  1.00  0.00     0.056 C
ENDBRANCH   6   9
ENDBRANCH   5   6
BRANCH   5  16
ATOM     16  C   UNL     1      -0.372  -1.261  -0.434  1.00  0.00     0.170 CG0
ATOM     17  G   UNL     1      -1.871  -1.537  -0.770  1.00  0.00     0.000 G0
ENDBRANCH   5  16
ENDBRANCH   4   5
ENDBRANCH   2   4
ENDBRANCH   1   2
BRANCH   1  18
ATOM     18  N   UNL     1      -2.568  -0.386  -1.415  1.00  0.00    -0.332 N
ATOM     19  C   UNL     1      -2.279  -0.330  -2.863  1.00  0.00     0.333 C
ATOM     20  H   UNL     1      -3.601  -0.551  -1.354  1.00  0.00     0.348 HD
BRANCH  18  21
ATOM     21  C   UNL     1      -1.871  -1.537  -0.770  1.00  0.00     0.225 CG0
ATOM     22  G   UNL     1      -0.372  -1.261  -0.434  1.00  0.00     0.000 G0
BRANCH  21  23
ATOM     23  C   UNL     1      -2.688  -2.101   0.430  1.00  0.00     0.226 C
BRANCH  23  24
ATOM     24  O   UNL     1      -2.576  -1.346   1.621  1.00  0.00    -0.375 OA
BRANCH  24  25
ATOM     25  C   UNL     1      -3.084  -0.037   1.465  1.00  0.00     0.171 CG1
ATOM     26  G   UNL     1      -2.092   0.900   0.733  1.00  0.00     0.000 G1
ENDBRANCH  24  25
ENDBRANCH  23  24
ENDBRANCH  21  23
ENDBRANCH  18  21
ENDBRANCH   1  18
TORSDOF 2

Is there an option in Meeko to automatically correct these atom types during PDBQT generation?
Any guidance you can provide would be greatly appreciated!

Thank you in advance.

Regards,

Ashish

**Comment by diogomart** [comment]
The atom types are correct, it's just that Vina GPU, which is not developed by us, doesn't support flexible macrocycles. Vina and autodock-gpu, which are developed by us, support flexible macrocycles. For Vina GPU you'll need to disable flexible macrocycles with `--rigid_macrocycles`

**Comment by aashuph16221** [comment]
Thank you for the help.

**Comment by diogomart** [comment]
You're welcome!
