### ISSUE TITLE
Question about the values assigned to exhaustiveness and num_modes

### ISSUE THREAD

**Issue by xavgit** [forlilab/Meeko#214]
Hi,
for vina ,can the values ​​assigned to exhaustiveness and num_modes be completely independent or 
must they be somehow dependent?
For example exhaustiveness = num_modes..
What are the commonly chosen values ​​for these options?
Does it make sense to set high values ​​than the common used for these options?

Thanks.

Saverio

**Comment by rwxayheee** [comment]
Hi @xavgit 
exhaustiveness doesn't need to be exactly num_modes. There are some related topics in the FAQ: https://autodock-vina.readthedocs.io/en/latest/faq.html
Vina's default num_modes is 9. In practice, this depends on whether your goal is to obtain more diverse poses from docking. A commonly used exhaustiveness is 32, but it may depend on the size of search space and the actual system.

**Comment by xavgit** [comment]
Thanks.
Sorry for the wrong place to post this question.

Saverio

**Comment by rwxayheee** [comment]
Hi @xavgit 
No worries at all. If you have any further questions, please feel free to reopen or leave a comment. Closing the issue for now
