### ISSUE TITLE
How to use arg "--add_index_map"?

### ISSUE THREAD

**Issue by Yongrui-Wang** [forlilab/Meeko#22]
Hello？
How does '--add_ index_ map' work? I tried to follow the txt file or write the center coordinates directly, but it didn't work

**Comment by diogomart** [comment]
Hi,

```mk_prepare_ligand.py -i molecule.sdf -o molecule.pdbqt --add_index_map```

Writes the mapping between PDBQT and SDF atom indices to lines starting with `REMARK INDEX MAP`

**Comment by Yongrui-Wang** [comment]
thanks!

**Comment by hima111997** [comment]
Hi can you please tell me what is the importance of add_index_map command. i have used it and these two lines were written in the pdbqt file:

```
REMARK INDEX MAP 13 1 14 2 15 3 16 4 17 5 18 6 2 7 1 8 4 9 3 10 5 11 7 12 8 13
REMARK INDEX MAP 12 14 9 15 11 16 10 17 6 18 24 19 19 20 20 21 21 22 22 23
```

originally i was searching for a way to keep the ordering of the atoms in the docked pdbqt files the same as the original .sdf file during redocking as i found out that calculating RMSD with two files having different atom orders produces large values in VMD. So when i found this command i thought maybe it will help but i could not use the new information in the pdbqt file when converting it so pdb to open it in VMD.

So can you help me with this problem?

Edit 1: i found another issue that describe the format of the index_map info. But mk_export does not return the original order. Should i write a python code the use this map and reorder the atoms and generate a reordered sdf file?

**Comment by diogomart** [comment]
Yes, you can do that, but I think it is easier to not use those indices: instead, use RDKit substructure matching directly. Or compute the RMSD in python: https://github.com/rdkit/rdkit/blob/master/Contrib/CalcLigRMSD/CalcLigRMSD.py

**Comment by hima111997** [comment]
I wrote a python code to convert from pdbqt to pdb using the reverse of the indices and it works well till now. Thank you for suggestion.

Yahoo Mail: Search, organise, conquer 
 
  On Fri, 8 Aug 2025 at 10:45 pm, ***@***.***> wrote:   diogomart left a comment (forlilab/Meeko#22)
Yes, you can do that, but I think it is easier to not use those indices: instead, use RDKit substructure matching directly. Or compute the RMSD in python: https://github.com/rdkit/rdkit/blob/master/Contrib/CalcLigRMSD/CalcLigRMSD.py
