### ISSUE TITLE
mk_copy_coords.py template not working

### ISSUE THREAD

**Issue by eneas77** [forlilab/Meeko#23]
Hi,

I´ve installed meeko 0.3.3 via conda. I´m unable to use the mk_copy_coords.py script as the argument -i is not recognized. Checking the code I can see there is no arg for the template section as it was before. Any chance to restore it?

Thanks,

E77

**Comment by diogomart** [comment]
Yes, sorry, I took it out before releasing 0.3.3 because we wanted to deprecate the feature, but then realized that some people might need it, so I added it back, but it isn't in a release yet. You can get it by installing from source:

```sh
git clone https://github.com/forlilab/Meeko
cd Meeko
pip install .
```
