### ISSUE TITLE
Link to readthedocs is broken

### ISSUE THREAD

**Issue by and-tos** [forlilab/Meeko#235]
The link to the docs in the Readme is broken:
[meeko.readthedocs.io](https://github.com/forlilab/Meeko/blob/release/meeko.readthedocs.io)

**Comment by rwxayheee** [comment]
It's currently 
https://meeko.readthedocs.io/en/release/

**Comment by diogomart** [comment]
Thanks! Links fixed in #238. Will take effect when we release `v0.6.1` as the default branch is `release`.
