### ISSUE TITLE
ATOM syntax incorrect: "CG0" is not a valid AutoDock type. 

### ISSUE THREAD

**Issue by SawanKumar23** [forlilab/Meeko#239]
I have downloaded the 3D conformer of Galantamine from Pubchem and prepared the Galantamine.sdf file to a pdbqt file using the mk_perpare_ligand.py script. Now, during docking through AutoDockVina, it shows this error. 
ATOM syntax incorrect: "CG0" is not a valid AutoDock type. Note that AutoDock atom types are case-sensitive.
Docking failed. 
How do we deal with this atom-type error? Please provide assistance on this. 
The below is the prepared pdbqt file.

REMARK SMILES COc1ccc2c3c1O[C@H]1C[C@@H](O)C=C[C@@]31CCN(C)C2
REMARK SMILES IDX 21 1 6 2 9 3 10 4 8 5 16 6 11 7 7 8 3 9 15 10 12 11 4 12
REMARK SMILES IDX 14 13 5 14 17 15 2 17 1 18 13 19 19 21 20 22 18 23
REMARK H PARENT 13 20
REMARK Flexibility Score: 90.00
ROOT
ATOM      1  C   UNL     1       2.720   0.577  -1.080  1.00  0.00     0.120 C 
ENDROOT
BRANCH   1   2
ATOM      2  C   UNL     1       1.422   1.158  -0.584  1.00  0.00    -0.026 A 
ATOM      3  O   UNL     1      -1.673   0.032   0.900  1.00  0.00    -0.485 OA
ATOM      4  C   UNL     1      -0.840  -1.124   1.176  1.00  0.00     0.191 C 
ATOM      5  C   UNL     1      -0.786   0.939   0.376  1.00  0.00     0.166 A 
ATOM      6  C   UNL     1       0.368  -1.109   0.185  1.00  0.00     0.056 C 
ATOM      7  C   UNL     1      -1.681  -2.401   1.101  1.00  0.00     0.082 C 
ATOM      8  C   UNL     1       0.418   0.372  -0.031  1.00  0.00     0.016 A 
ATOM      9  C   UNL     1      -1.055   2.286   0.238  1.00  0.00     0.161 A 
ATOM     10  C   UNL     1       0.060  -1.833  -1.112  1.00  0.00    -0.013 C 
ATOM     11  C   UNL     1      -2.138  -2.729  -0.323  1.00  0.00     0.140 C 
ATOM     12  C   UNL     1      -0.061   3.090  -0.315  1.00  0.00     0.051 A 
ATOM     13  C   UNL     1      -1.060  -2.534  -1.340  1.00  0.00     0.001 C 
ATOM     14  C   UNL     1       1.163   2.533  -0.721  1.00  0.00     0.009 A 
BRANCH   6  15
ATOM     15  C   UNL     1       1.621  -1.681   0.879  1.00  0.00     0.035 CG0
ATOM     16  G   UNL     1       2.944  -1.577   0.104  1.00  0.00     0.000 G0
ENDBRANCH   6  15
BRANCH   9  17
ATOM     17  O   UNL     1      -2.239   2.818   0.631  1.00  0.00    -0.493 OA
ATOM     18  C   UNL     1      -3.291   2.861  -0.335  1.00  0.00     0.278 C 
ENDBRANCH   9  17
BRANCH  11  19
ATOM     19  O   UNL     1      -3.243  -1.910  -0.694  1.00  0.00    -0.389 OA
ATOM     20  H   UNL     1      -3.543  -2.194  -1.574  1.00  0.00     0.211 HD
ENDBRANCH  11  19
ENDBRANCH   1   2
BRANCH   1  21
ATOM     21  N   UNL     1       3.483  -0.239  -0.134  1.00  0.00    -0.302 NA
ATOM     22  C   UNL     1       3.869   0.471   1.079  1.00  0.00     0.105 C 
BRANCH  21  23
ATOM     23  C   UNL     1       2.944  -1.577   0.104  1.00  0.00     0.086 CG0
ATOM     24  G   UNL     1       1.621  -1.681   0.879  1.00  0.00     0.000 G0
ENDBRANCH  21  23
ENDBRANCH   1  21
TORSDOF 2

**Comment by diogomart** [comment]
It's for macrocycle sampling (see #158). Using latest vina (v1.2.5 at the moment) instead of v1.1.2 will fix it.
See also #28, #70, #71, #99, #212.
