### ISSUE TITLE
Meeko does not add water molecules to some ligands

### ISSUE THREAD

**Issue by isilkajun** [forlilab/Meeko#26]
Hi,
I am working hydrated docking with a large drug library.  Meeko does not add water molecules to some of these drugs. I'm attaching one of the examples.
[compound1068.tar.gz](https://github.com/forlilab/Meeko/files/9234241/compound1068.tar.gz)

**Comment by diogomart** [comment]
Hi,
Meeko adds waters only to hydrogen bond sites (see [paper](https://pubs.acs.org/doi/abs/10.1021/jm2005145)). This molecule does not have H-bond sites, so no waters are added. This is a harsh approximation to reality, where water would interact strongly with the charged methylated ammoniuns, but on the other hand I don't know if there are complexes in which a water binds between the protein and a methylated ammonium.

**Comment by isilkajun** [comment]
I missed this information, thank you.

**Comment by diogomart** [comment]
You are welcome
