### ISSUE TITLE
Hydrogen addition prior to mk_prepare_receptor

### ISSUE THREAD

**Issue by frgoe003** [forlilab/Meeko#262]
I have some questions about the Meeko receptor preparation in general:
In the Google Colab example, you use reduce2 to first add hydrogens to the receptor - is this step still necessary with the latest Meeko version? I found reduce2 quite difficult to install.

**Comment by rwxayheee** [comment]
Hi @frgoe003 
Reduce2.py includes hydrogen addition and optimization (of hydrogen bond network and orientations of residues like His, Asn, Gln), which we might find useful. In Meeko hydrogens are added according to valence and the position is taken as is. 
You can take a look at how reduce2 is installed in the environment for the Colab. It has some dependencies, and I tried to set up the minimal configuration to be able to run reduce2.

**Comment by diogomart** [comment]
@frgoe003 doesn't `micromamba install cctbx-base` work for you? This is how it is installed in the "basic docking" notebook in the [Meeko Colab examples](https://meeko.readthedocs.io/en/release/colab_examples.html).

**Comment by frgoe003** [comment]
Thanks @rwxayheee and @diogomart, reduce2 works now.
