### ISSUE TITLE
 ATOM syntax incorrect: "CG0" is not a valid AutoDock type

### ISSUE THREAD

**Issue by gkxiao** [forlilab/Meeko#28]
<h3>1. step to reproduce the error</h3>
<pre line="1" lang="python">
vina --config dock.conf --receptor 1ajv_rec.pdbqt --ligand 1ajv_lig.pdbqt --out 1ajv_lig_out.pdbqt
#################################################################
# If you used AutoDock Vina in your work, please cite:          #
#                                                               #
# O. Trott, A. J. Olson,                                        #
# AutoDock Vina: improving the speed and accuracy of docking    #
# with a new scoring function, efficient optimization and       #
# multithreading, Journal of Computational Chemistry 31 (2010)  #
# 455-461                                                       #
#                                                               #
# DOI 10.1002/jcc.21334                                         #
#                                                               #
# Please see http://vina.scripps.edu for more information.      #
#################################################################

Detected 56 CPUs
WARNING: at low exhaustiveness, it may be impossible to utilize all CPUs
Reading input ...

Parse error on line 16 in file "1ajv_lig.pdbqt": ATOM syntax incorrect: "CG0" is not a valid AutoDock type. Note that AutoDock atom types are case-sensitive.
</pre>
<h3>2. prepare ligand file</h3>
<pre line="1" lang="python">
mk_prepare_ligand.py -i 1ajv_lig.sdf -o 1ajv_lig.pdbqt
</pre>
<h3>3. the ligand file: lajv_lig.pdbqt</h3>
<pre line="1" lang="python">
REMARK SMILES O=S1(=O)N(Cc2ccccc2)C(COc2ccccc2)C(O)C(O)C(COc2ccccc2)N1Cc1ccccc1
REMARK SMILES IDX 2 1 1 2 3 3 34 4 25 5 26 7 27 8 28 9 29 10 33 11 30 12 32 13
REMARK SMILES IDX 31 14 35 15 36 16 37 17 41 18 38 19 40 20 39 21 4 22 12 23
REMARK SMILES IDX 21 24 23 25 24 27 22 29 13 31 14 32 15 33 16 34 20 35 17 36
REMARK SMILES IDX 19 37 18 38 5 39 6 40 7 41 11 42 8 43 10 44 9 45
REMARK H PARENT 24 28 22 30
REMARK Flexibility Score: 80.00
ROOT
ATOM      1  S   UNL     1      11.752  21.994   6.409  1.00  0.00     0.283 S
ATOM      2  O   UNL     1      11.195  20.919   5.621  1.00  0.00    -0.195 OA
ATOM      3  O   UNL     1      11.563  21.966   7.821  1.00  0.00    -0.195 OA
ENDROOT
BRANCH   1   4
ATOM      4  N   UNL     1      11.288  23.491   5.863  1.00  0.00    -0.175 NA
BRANCH   4   5
ATOM      5  C   UNL     1      11.470  24.031   4.534  1.00  0.00     0.143 CG0
ATOM      6  G   UNL     1      12.964  24.314   4.550  1.00  0.00     0.000 G0
BRANCH   5   7
ATOM      7  C   UNL     1      10.812  23.139   3.466  1.00  0.00     0.252 C
BRANCH   7   8
ATOM      8  O   UNL     1       9.388  23.235   3.713  1.00  0.00    -0.492 OA
BRANCH   8   9
ATOM      9  C   UNL     1       8.638  24.096   2.999  1.00  0.00     0.119 A
ATOM     10  C   UNL     1       9.186  25.297   2.506  1.00  0.00     0.046 A
ATOM     11  C   UNL     1       7.299  23.816   2.745  1.00  0.00     0.046 A
ATOM     12  C   UNL     1       8.412  26.203   1.767  1.00  0.00     0.004 A
ATOM     13  C   UNL     1       6.507  24.722   2.007  1.00  0.00     0.004 A
ATOM     14  C   UNL     1       7.065  25.914   1.516  1.00  0.00     0.000 A
ENDBRANCH   8   9
ENDBRANCH   7   8
ENDBRANCH   5   7
ENDBRANCH   4   5
BRANCH   4  15
ATOM     15  C   UNL     1      10.097  23.950   6.436  1.00  0.00     0.139 C
BRANCH  15  16
ATOM     16  C   UNL     1       9.759  25.135   7.273  1.00  0.00    -0.033 A
ATOM     17  C   UNL     1       8.526  25.784   7.141  1.00  0.00     0.005 A
ATOM     18  C   UNL     1      10.716  25.613   8.206  1.00  0.00     0.005 A
ATOM     19  C   UNL     1       8.230  26.897   7.929  1.00  0.00     0.000 A
ATOM     20  C   UNL     1      10.431  26.739   9.009  1.00  0.00     0.000 A
ATOM     21  C   UNL     1       9.185  27.378   8.869  1.00  0.00     0.000 A
ENDBRANCH  15  16
ENDBRANCH   4  15
ENDBRANCH   1   4
BRANCH   1  22
ATOM     22  N   UNL     1      13.339  22.051   6.143  1.00  0.00    -0.175 NA
BRANCH  22  23
ATOM     23  C   UNL     1      13.718  21.882   4.715  1.00  0.00     0.143 C
BRANCH  23  24
ATOM     24  C   UNL     1      13.866  23.222   4.019  1.00  0.00     0.166 C
BRANCH  24  25
ATOM     25  C   UNL     1      12.964  24.314   4.550  1.00  0.00     0.166 CG0
ATOM     26  G   UNL     1      11.470  24.031   4.534  1.00  0.00     0.000 G0
BRANCH  25  27
ATOM     27  O   UNL     1      13.282  25.492   3.848  1.00  0.00    -0.389 OA
ATOM     28  H   UNL     1      12.723  26.215   4.162  1.00  0.00     0.211 HD
ENDBRANCH  25  27
ENDBRANCH  24  25
BRANCH  24  29
ATOM     29  O   UNL     1      15.185  23.696   4.171  1.00  0.00    -0.389 OA
ATOM     30  H   UNL     1      15.274  24.550   3.726  1.00  0.00     0.211 HD
ENDBRANCH  24  29
ENDBRANCH  23  24
BRANCH  23  31
ATOM     31  C   UNL     1      14.980  21.017   4.548  1.00  0.00     0.252 C
BRANCH  31  32
ATOM     32  O   UNL     1      14.762  20.021   3.521  1.00  0.00    -0.492 OA
BRANCH  32  33
ATOM     33  C   UNL     1      15.758  19.150   3.211  1.00  0.00     0.119 A
ATOM     34  C   UNL     1      16.685  18.752   4.198  1.00  0.00     0.046 A
ATOM     35  C   UNL     1      15.866  18.632   1.912  1.00  0.00     0.046 A
ATOM     36  C   UNL     1      17.711  17.848   3.882  1.00  0.00     0.004 A
ATOM     37  C   UNL     1      16.880  17.726   1.585  1.00  0.00     0.004 A
ATOM     38  C   UNL     1      17.804  17.334   2.569  1.00  0.00     0.000 A
ENDBRANCH  32  33
ENDBRANCH  31  32
ENDBRANCH  23  31
ENDBRANCH  22  23
BRANCH  22  39
ATOM     39  C   UNL     1      14.199  22.696   7.160  1.00  0.00     0.139 C
BRANCH  39  40
ATOM     40  C   UNL     1      15.185  21.856   7.925  1.00  0.00    -0.033 A
ATOM     41  C   UNL     1      14.748  20.969   8.940  1.00  0.00     0.005 A
ATOM     42  C   UNL     1      16.558  21.938   7.631  1.00  0.00     0.005 A
ATOM     43  C   UNL     1      15.687  20.170   9.651  1.00  0.00     0.000 A
ATOM     44  C   UNL     1      17.495  21.147   8.336  1.00  0.00     0.000 A
ATOM     45  C   UNL     1      17.061  20.260   9.346  1.00  0.00     0.000 A
ENDBRANCH  39  40
ENDBRANCH  22  39
ENDBRANCH   1  22
TORSDOF 12
</pre>
<h3>4. lajv_lig.sdf</h3>
<pre  line="1" lang="python">
1ajv_ligand
  xed2sdf_05210316543D

 75 79  0  0  1  0  0  0  0  0999 V2000
   11.2880   23.4910    5.8630 N   0  0  0  0  0  0  0  0  0  0  0  0
   11.7520   21.9940    6.4090 S   0  0  0  0  0  0  0  0  0  0  0  0
   13.3390   22.0510    6.1430 N   0  0  0  0  0  0  0  0  0  0  0  0
   13.7180   21.8820    4.7150 C   0  0  0  0  0  0  0  0  0  0  0  0
   13.8660   23.2220    4.0190 C   0  0  0  0  0  0  0  0  0  0  0  0
   12.9640   24.3140    4.5500 C   0  0  0  0  0  0  0  0  0  0  0  0
   11.4700   24.0310    4.5340 C   0  0  0  0  0  0  0  0  0  0  0  0
   10.0970   23.9500    6.4360 C   0  0  0  0  0  0  0  0  0  0  0  0
    9.7590   25.1350    7.2730 C   0  0  0  0  0  0  0  0  0  0  0  0
    8.5260   25.7840    7.1410 C   0  0  0  0  0  0  0  0  0  0  0  0
    8.2300   26.8970    7.9290 C   0  0  0  0  0  0  0  0  0  0  0  0
    9.1850   27.3780    8.8690 C   0  0  0  0  0  0  0  0  0  0  0  0
   10.4310   26.7390    9.0090 C   0  0  0  0  0  0  0  0  0  0  0  0
   10.7160   25.6130    8.2060 C   0  0  0  0  0  0  0  0  0  0  0  0
   11.1950   20.9190    5.6210 O   0  0  0  0  0  0  0  0  0  0  0  0
   14.7620   20.0210    3.5210 O   0  0  0  0  0  0  0  0  0  0  0  0
   15.7580   19.1500    3.2110 C   0  0  0  0  0  0  0  0  0  0  0  0
   16.6850   18.7520    4.1980 C   0  0  0  0  0  0  0  0  0  0  0  0
   17.7110   17.8480    3.8820 C   0  0  0  0  0  0  0  0  0  0  0  0
   17.8039   17.3340    2.5690 C   0  0  0  0  0  0  0  0  0  0  0  0
   16.8800   17.7260    1.5850 C   0  0  0  0  0  0  0  0  0  0  0  0
   15.8660   18.6320    1.9120 C   0  0  0  0  0  0  0  0  0  0  0  0
   14.1990   22.6960    7.1600 C   0  0  0  0  0  0  0  0  0  0  0  0
   15.1850   21.8560    7.9250 C   0  0  0  0  0  0  0  0  0  0  0  0
   14.7480   20.9690    8.9400 C   0  0  0  0  0  0  0  0  0  0  0  0
   15.6870   20.1700    9.6510 C   0  0  0  0  0  0  0  0  0  0  0  0
   17.0610   20.2600    9.3460 C   0  0  0  0  0  0  0  0  0  0  0  0
   17.4950   21.1470    8.3360 C   0  0  0  0  0  0  0  0  0  0  0  0
   16.5580   21.9380    7.6310 C   0  0  0  0  0  0  0  0  0  0  0  0
   15.1850   23.6960    4.1710 O   0  0  0  0  0  0  0  0  0  0  0  0
   13.2820   25.4920    3.8480 O   0  0  0  0  0  0  0  0  0  0  0  0
   10.8120   23.1390    3.4660 C   0  0  0  0  0  0  0  0  0  0  0  0
    9.3880   23.2350    3.7130 O   0  0  0  0  0  0  0  0  0  0  0  0
    8.6380   24.0960    2.9990 C   0  0  0  0  0  0  0  0  0  0  0  0
    9.1860   25.2970    2.5060 C   0  0  0  0  0  0  0  0  0  0  0  0
    8.4120   26.2030    1.7670 C   0  0  0  0  0  0  0  0  0  0  0  0
    7.0650   25.9140    1.5160 C   0  0  0  0  0  0  0  0  0  0  0  0
    6.5070   24.7220    2.0070 C   0  0  0  0  0  0  0  0  0  0  0  0
    7.2990   23.8160    2.7450 C   0  0  0  0  0  0  0  0  0  0  0  0
   11.5630   21.9660    7.8210 O   0  0  0  0  0  0  0  0  0  0  0  0
   14.9800   21.0170    4.5480 C   0  0  0  0  0  0  0  0  0  0  0  0
   12.9690   21.3250    4.2150 H   0  0  0  0  0  0  0  0  0  0  0  0
   13.6400   23.1120    2.9900 H   0  0  0  0  0  0  0  0  0  0  0  0
   13.2090   24.5140    5.5610 H   0  0  0  0  0  0  0  0  0  0  0  0
   10.8730   24.8980    4.4210 H   0  0  0  0  0  0  0  0  0  0  0  0
    9.3850   24.1320    5.6730 H   0  0  0  0  0  0  0  0  0  0  0  0
    9.7210   23.2180    7.1020 H   0  0  0  0  0  0  0  0  0  0  0  0
    7.8020   25.4250    6.4290 H   0  0  0  0  0  0  0  0  0  0  0  0
    7.2790   27.3920    7.8260 H   0  0  0  0  0  0  0  0  0  0  0  0
    8.9560   28.2360    9.4780 H   0  0  0  0  0  0  0  0  0  0  0  0
   11.1500   27.1100    9.7200 H   0  0  0  0  0  0  0  0  0  0  0  0
   11.6660   25.1160    8.3050 H   0  0  0  0  0  0  0  0  0  0  0  0
   16.6070   19.1420    5.1990 H   0  0  0  0  0  0  0  0  0  0  0  0
   18.4190   17.5520    4.6370 H   0  0  0  0  0  0  0  0  0  0  0  0
   18.5860   16.6380    2.3170 H   0  0  0  0  0  0  0  0  0  0  0  0
   16.9560   17.3290    0.5870 H   0  0  0  0  0  0  0  0  0  0  0  0
   15.1630   18.9310    1.1530 H   0  0  0  0  0  0  0  0  0  0  0  0
   14.7910   23.4440    6.6990 H   0  0  0  0  0  0  0  0  0  0  0  0
   13.5920   23.1370    7.9070 H   0  0  0  0  0  0  0  0  0  0  0  0
   13.7000   20.8970    9.1770 H   0  0  0  0  0  0  0  0  0  0  0  0
   15.3480   19.4980   10.4210 H   0  0  0  0  0  0  0  0  0  0  0  0
   17.7720   19.6540    9.8820 H   0  0  0  0  0  0  0  0  0  0  0  0
   18.5430   21.2230    8.1000 H   0  0  0  0  0  0  0  0  0  0  0  0
   16.9050   22.6080    6.8620 H   0  0  0  0  0  0  0  0  0  0  0  0
   15.2740   24.5500    3.7260 H   0  0  0  0  0  0  0  0  0  0  0  0
   12.7230   26.2150    4.1620 H   0  0  0  0  0  0  0  0  0  0  0  0
   11.0640   23.4980    2.5020 H   0  0  0  0  0  0  0  0  0  0  0  0
   11.1590   22.1440    3.5740 H   0  0  0  0  0  0  0  0  0  0  0  0
   10.2190   25.5350    2.6940 H   0  0  0  0  0  0  0  0  0  0  0  0
    8.8540   27.1130    1.3970 H   0  0  0  0  0  0  0  0  0  0  0  0
    6.4630   26.6040    0.9490 H   0  0  0  0  0  0  0  0  0  0  0  0
    5.4710   24.4960    1.8210 H   0  0  0  0  0  0  0  0  0  0  0  0
    6.8610   22.9030    3.1120 H   0  0  0  0  0  0  0  0  0  0  0  0
   15.7960   21.6330    4.2700 H   0  0  0  0  0  0  0  0  0  0  0  0
   15.2000   20.5320    5.4640 H   0  0  0  0  0  0  0  0  0  0  0  0
  1  2  1  0
  2  3  1  0
  3  4  1  0
  4 42  1  0
  4  5  1  0
  5 43  1  0
  5  6  1  0
  6 44  1  0
  1  7  1  0
  6  7  1  0
  7 45  1  0
  1  8  1  0
  8 46  1  0
  8 47  1  0
  8  9  1  0
  9 10  2  0
 10 48  1  0
 10 11  1  0
 11 49  1  0
 11 12  2  0
 12 50  1  0
 12 13  1  0
 13 51  1  0
  9 14  1  0
 13 14  2  0
 14 52  1  0
  2 15  2  0
 16 17  1  0
 17 18  2  0
 18 53  1  0
 18 19  1  0
 19 54  1  0
 19 20  2  0
 20 55  1  0
 20 21  1  0
 21 56  1  0
 17 22  1  0
 21 22  2  0
 22 57  1  0
  3 23  1  0
 23 58  1  0
 23 59  1  0
 23 24  1  0
 24 25  2  0
 25 60  1  0
 25 26  1  0
 26 61  1  0
 26 27  2  0
 27 62  1  0
 27 28  1  0
 28 63  1  0
 24 29  1  0
 28 29  2  0
 29 64  1  0
  5 30  1  0
 30 65  1  0
  6 31  1  0
 31 66  1  0
  7 32  1  0
 32 67  1  0
 32 68  1  0
 32 33  1  0
 33 34  1  0
 34 35  2  0
 35 69  1  0
 35 36  1  0
 36 70  1  0
 36 37  2  0
 37 71  1  0
 37 38  1  0
 38 72  1  0
 34 39  1  0
 38 39  2  0
 39 73  1  0
  2 40  2  0
  4 41  1  0
 16 41  1  0
 41 74  1  0
 41 75  1  0
M  END
$$$$
</pre>

**Comment by diogomart** [comment]
You need vina 1.2.3, not vina 1.1.2

**Comment by gkxiao** [comment]
It is my wrong. It works. Thank you very much.
