### ISSUE TITLE
Low Dielectric Value Observed in GPF File from Meeko Tutorial

### ISSUE THREAD

**Issue by yuki3343** [forlilab/Meeko#281]
Hello,

I am currently following the Meeko tutorial to create the gpf and maps.fld files required for AutoDock-GPU.

When I ran the following command, the terminal output matched the tutorial, and a gpf file was successfully generated. However, I noticed that the dielectric value in the gpf file is -42.000, which is significantly lower compared to the value generated using the AutoDockTools([-0.1465]). Is this behavior expected? I also tried installing Meeko via pip, but the same behavior was observed.

**input**
`pdb_file="1iep_protein.pdb"
lig_file="xray-imatinib.pdb"
mk_prepare_receptor.py --read_pdb $pdb_file -o rec_1iep -p -g \
--box_enveloping $lig_file --padding 5`

**output**
`Files written:
            rec_1iep.pdbqt <-- static (i.e., rigid) receptor input file
boron-silicon-atom_par.dat <-- atomic parameters for B and Si (for autogrid)
              rec_1iep.gpf <-- autogrid input file
          rec_1iep.box.pdb <-- PDB file to visualize the grid box`

**gpf : rec_1iep.gpf**
parameter_file boron-silicon-atom_par.dat
npts 48 70 62
gridfld rec_1iep.maps.fld
spacing 0.375
receptor_types HD C A N NA OA F P SA S Cl Br I Mg Ca Mn Fe Zn
ligand_types HD C A N NA OA F P SA S Cl CL Br BR I Si B
receptor rec_1iep.pdbqt
gridcenter 15.190 53.903 16.917
smooth 0.500
map rec_1iep.HD.map
map rec_1iep.C.map
map rec_1iep.A.map
map rec_1iep.N.map
map rec_1iep.NA.map
map rec_1iep.OA.map
map rec_1iep.F.map
map rec_1iep.P.map
map rec_1iep.SA.map
map rec_1iep.S.map
map rec_1iep.Cl.map
map rec_1iep.CL.map
map rec_1iep.Br.map
map rec_1iep.BR.map
map rec_1iep.I.map
map rec_1iep.Si.map
map rec_1iep.B.map
elecmap rec_1iep.e.map
dsolvmap rec_1iep.d.map
dielectric -42.000

**meeko version**
meeko                     0.6.1              pyhd8ed1ab_0    conda-forge 

Thanks in advance for any help/tips.

**Comment by rwxayheee** [comment]
Hi @yuki3343! 

Actually this exact value won't be used. See AutoDock4 Manual pp.32: https://autodock.scripps.edu/wp-content/uploads/sites/56/2021/10/AutoDock4.2.6_UserGuide.pdf

> dielectric <float>
> [-0.1465]
> (Optional) Dielectric function flag: if negative, AutoGrid will use distance-dependent dielectric
> of Mehler and Solmajer; if the float is positive, AutoGrid will use this value as the dielectric
> constant. AutoDock4 has been calibrated to use a value of –0.1465

(in other words, as long as the number is negative the exact value doesn't matter, in my understanding)

**Comment by yuki3343** [comment]
Thank you very much for your prompt and helpful response. 
I realize now that the issue was due to a very basic oversight on my part. I truly appreciate your patience and guidance, and I apologize for any inconvenience caused by my mistake.

**Comment by rwxayheee** [comment]
Hi @yuki3343 
No problem at all. You're very welcome. If you have any more questions, please feel free to leave a comment or reopen the issue.
