### ISSUE TITLE
About mk_prepare_receptor.py  Python API

### ISSUE THREAD

**Issue by sasaju** [forlilab/Meeko#284]
I noticed that there is a related Python API for ligand preparation with documentation available at https://meeko.readthedocs.io/en/release/lig_prep_basic.html#python-api. However, I couldn't find a Python API in the receptor preparation section(https://meeko.readthedocs.io/en/release/cli_rec_prep.html). 
Is there a related API and documentation?
Thanks.

**Comment by diogomart** [comment]
There is an API but we didn't document it. At least not yet. The best for now is to read through [mk_prepare_receptor.py](https://github.com/forlilab/Meeko/blob/release/meeko/cli/mk_prepare_receptor.py) to see how the API is used. Automating receptor preparation is more difficult than ligand preparation as there are more variables to consider, such as keeping waters or not, making sidechains flexible, handling missing atoms, or rotating hydroxyl groups. Thus, we envisioned that it would be more common to use the command line script to interactively prepare a receptor, save a serialized receptor to a JSON file, and then use the JSON file in scripts.

**Comment by sasaju** [comment]
Thanks for your response!
