### ISSUE TITLE
About parameters of pseudoatoms CGn and Gn for further Autogrid4

### ISSUE THREAD

**Issue by songyingit** [forlilab/Meeko#30]
Hello,

Recently I read the paper on chemrxiv (https://doi.org/10.26434/chemrxiv-2022-txdt0). It's an amazing work so I also want to try Autodock-GPU for my peptide systems. But, after the .gpf file was generated, when I use autogrid4 to generate the map.fld file, I met this error:
```
ERROR:  unknown ligand atom type G0
add parameters for it to the parameter library first!
```
I think this happened because no parameters of pseudoatoms CGn and Gn in parameter library of Autogrid. Therefore, may I ask about where could I get the parameters for these pseudoatoms CGn and Gn?

Thanks,
Song

**Comment by diogomart** [comment]
Hello,
I suspect we might have a problem with our documentation regarding autogrid and the .gpf file. How did you produce the .gpf file?

**Comment by diogomart** [comment]
AD-GPU and Vina do not require maps for those types, so there's no need to compute them with autogrid. [This script](https://github.com/diogomart/write-autogrid-config) may help.

**Comment by songyingit** [comment]
Hello, thanks for the reply!

I used the `prepare_receptor4.py` in **AutodockTools** to prepare the .pdbqt file for receptor 
And then used `mk_prepare_ligand.py` in **Meeko** to prepare the .pdbqt file for ligand (also use this flag: "-r C=C-C=A -b 2 3" to disable the rotation of conjugated bonds based on the paper)
Then I use `prepare_gpf4.py` in **AutodockTools** to produce .gpf file. The command is  `prepare_gpf4.py -l ligand.pdbqt -r protein.pdbqt -y `
It works until I try to use Autogrid4 to produce the map.fld file. The command I used here is `autogrid4 -p protein.gpf `. It showed the error:
```
ERROR:  unknown ligand atom type G0
add parameters for it to the parameter library first!
```
I think it should be the same case for CG0, which is another pseudoatom.

BTW, previously, when I used  to `prepare_ligand4.py` in **AutodockTools** to prepare the .pdbqt file for ligand, it doesn't show any error when I try to get the map.fld file. But when I use this to run **Autodock-GPU**, it couldn't predict any samples. I think it may be because the peptide I am docking is large (~19 residues), and there are more than 20 rotatable bonds. That's why I want to follow this paper's process to use **Meeko** to take care of preparing ligand file. 

I appreciate if more details could be discussed.

Thanks,
Song

**Comment by diogomart** [comment]
Thank you for explaining your steps thoroughly. `prepare_gpf4.py` considers only the atom types in the ligand, but usually it's more efficient to run autogrid once for all atom types that may occur in ligands, enabling docking of any ligand without further autogrid calls. This is what  [the other script](https://github.com/diogomart/write-autogrid-config) does. It will help in your case specifically because the CGn/Gn atom types are not added to the GPF. Eventually, we'll probably stop recommending `prepare_gpf4.py` and use [the other script](https://github.com/diogomart/write-autogrid-config) instead.

**Comment by songyingit** [comment]
Thank you so much for the script. I have tried this script to prepare .gpf file for my systems, and it could work now. 

Best,
Song
