### ISSUE TITLE
Rdkit kekulize error

### ISSUE THREAD

**Issue by BJWiley233** [forlilab/Meeko#36]
Was hoping you could test this molecule for me.  I am getting [this error](https://github.com/rdkit/rdkit/issues/1397) from rdkit as Greg describes and the conversion fails.  I also get it for MANY other molecules.  I don't get issue with prepare_ligand from AD4 obviously cause it doesn't use rdkit.  The input molecule is here: https://drive.google.com/file/d/1u4OcKT7b-ULPb09DEeArLb_J7VyzFw_I/view?usp=sharing

```
[07:14:52] Can't kekulize mol.  Unkekulized atoms: 11 12 13 14 17
[07:14:52] sanitise [07:14:52] *****
```

I created the molecule from the smiles like:
```
obabel -:"CCCN[C@H]1CCCN(C(=O)c2cnn(CC)c2C)C1" -omol2 --gen3D -O ZINC001000520650.mol2
```
The structure looks fine in PyMol and matches the structure here: https://zinc15.docking.org/substances/ZINC001000520650/
![image](https://user-images.githubusercontent.com/26236052/203251523-995a583d-d64c-4748-8e9b-2978c47a0280.png)

**Comment by BJWiley233** [comment]
Ahh I bet it's because I am reading in mol2 files which was was AD4 took in but Rdkit does away with mol2 files as described by Greg (again :smile:) https://github.com/rdkit/rdkit/discussions/3647

Might want to add a note about this in the markdown if people are coming from the ADTools for AD4's prepare_ligand which I think only took mol2 files and didn't take sdf files.

**Comment by diogomart** [comment]
Yeah, even pyrazole (`"c2cn[nH]c2") would cause trouble. Related issues:
- https://github.com/rdkit/rdkit/issues/1755
- https://github.com/rdkit/rdkit/issues/917

Interestingly, in [this RDKit MOL2 test file](https://github.com/rdkit/rdkit/blob/adfdeca5113ca53cdf9b607b58084a895233dfaf/Code/GraphMol/FileParsers/test_data/pyrazole_pyridine.mol2), the atom types are aromatic for pyridine but not for pyrazole.

Will strengthen our SDF recommendation in the README.
