### ISSUE TITLE
write_pdbqt_string error for large molecules (protein)

### ISSUE THREAD

**Issue by QJ-Chen** [forlilab/Meeko#42]
For class `RDKitMoleculeSetup` in molsetup.py:
```
def find_pattern(self, smarts):
    p = Chem.MolFromSmarts(smarts)
    return self.mol.GetSubstructMatches(p)
```
mol.GetSubstructMatches has a default parameter `maxMatches=1000`. For mol with more than 1000 same element, e.g. C, excess atoms will not be setup.

**Comment by diogomart** [comment]
Yeah, large molecules or polymers are not really the main focus of the RDKit or Meeko.

**Comment by diogomart** [comment]
Meeko will start writing PDBQT strings for the receptor as well when we release v0.5, but it won't rely on RDKit. Instead, it will rely on  tabulated AD4 atom types and Gasteiger charges and indexed by residue and atom names according to Amber naming. So, it will be limited to a subset of stardard residues, at least in the beggining.
