### ISSUE TITLE
Meeko -m Unrecognized for Preparing Macrocycles

### ISSUE THREAD

**Issue by selmifiqhi** [forlilab/Meeko#44]
Hello, I used meeko 0.4.0 to prepared macrocycles compound and run this code.
 
` mk_prepare_ligand.py -i PPD_A.sdf -m -o PPD.pdbqt`

But the meeko give error message like this:

`mk_prepare_ligand.py: error: unrecognized arguments: -m`

Is there any change in the argument?
Thank you.

**Comment by diogomart** [comment]
Yes, we dropped the `-m` option, now macrocycles are flexible by default.
