### ISSUE TITLE
Problem about prepared ligand hydrogen

### ISSUE THREAD

**Issue by FeiLiuEM** [forlilab/Meeko#49]
Hello,

I have a problem about `mk_prepare_ligand.py`.

I use `mk_prepare_ligand.py -i ligand.sdf -o ligand.pdbqt` to prepare ligand. However, when I open `ligand.pdbqt` by `pymol`. I find that it could use `h_add` to add hydrogen for the `pdbqt` file.

I don't know why it happens. So, I have 2 questions:
1. Is this because I didn't add `keep_nonpolar_hydrogens=True`?
2. Does it affect the outcome of docking?

**Comment by diogomart** [comment]
Hello, the PDBQT are supposed to have only polar hydrogens, which are those bound to oxygen and nitrogen for most molecules. If you are missing those hydrogens, it's a problem. Non-polar hydrogens (e.g. bound to carbon) should not be there.

**Comment by FeiLiuEM** [comment]
Thank you diogomart! @diogomart 

You solved big problems for me.

Thanks ever so.
