### ISSUE TITLE
Cannot read ions with PDBQTMolecule

### ISSUE THREAD

**Issue by xrobin** [forlilab/Meeko#57]
I can't read PDBQT files of ions (Mg, Na, Ca, Zn, etc). Trying to read such a PDBQT fails with a TypeError.

Here is a minimal example:

```
pdbqt_str = """REMARK SMILES [Mg+2]
REMARK SMILES IDX 1 1
REMARK H PARENT
REMARK Flexibility Score: inf
ROOT
ATOM      1  Mg  UNL     1       0.000   0.000   0.000  1.00  0.00     2.000 Mg
ENDROOT
TORSDOF 0"""

from meeko import PDBQTMolecule
PDBQTMolecule(pdbqt_str)
```

Gives me the following error message:

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/xavier/venv/lib/python3.9/site-packages/meeko/molecule_pdbqt.py", line 338, in __init__
    self._bonds = _identify_bonds(self._atom_annotations['ligand'], mol_atoms['xyz'], mol_atoms['atom_type'])
  File "/home/xavier/venv/lib/python3.9/site-packages/meeko/molecule_pdbqt.py", line 292, in _identify_bonds
    optimal_distances = [bond_allowance_factor * (r_cov + covalent_radius[autodock4_atom_types_elements[atom_types[i]]]) for i in indices[1:]]
TypeError: 'int' object is not subscriptable
```

This is with Meeko 0.4 and Python 3.9.5 (installed with pip into a virtual environment). PDBQT file was created with the `mk_prepare_ligand.py` script (converted from RDKit SDF).

As a workaround, setting `skip_typing=True` allows the molecule to be read:

```
PDBQTMolecule(pdbqt_str, skip_typing=True)
# <Molecule named None containing 1 poses of 1 atoms>
```

**Comment by jeeberhardt** [comment]
Hi,

One solution would be to check if there the number of atoms present in the molecule. If there is only one, just return an empty dictionary. Does it sound good to you @diogomart ?

Here my suggestion (starting at line 309 of `molecule_pdbqt.py`):

```

def _identify_bonds(atom_idx, positions, atom_types):
    bonds = defaultdict(list)
    KDTree = spatial.cKDTree(positions)
    bond_allowance_factor = 1.1
    # If we ask more than the number of coordinates/element
    # in the BHTree, we will end up with some inf values
    k = 5 if len(atom_idx) > 5 else len(atom_idx)
    atom_idx = np.array(atom_idx)

    # If there is only one atom, we know there won't be a single bond..
    if len(atom_idx) == 1:
        return bonds

    for atom_i, position, atom_type in zip(atom_idx, positions, atom_types):
        distances, indices = KDTree.query(position, k=k)
        r_cov = covalent_radius[autodock4_atom_types_elements[atom_type]]

        optimal_distances = [bond_allowance_factor * (r_cov + covalent_radius[autodock4_atom_types_elements[atom_types[i]]]) for i in indices[1:]]
        bonds[atom_i] = atom_idx[indices[1:][np.where(distances[1:] < optimal_distances)]].tolist()

    return bonds
 
 ```

**Comment by diogomart** [comment]
@jeeberhardt yes that works

@xrobin is it always a single atom?

**Comment by jeeberhardt** [comment]
Yep, all the "normal" small molecules are going through without problem, and only ions are generating this issue.

**Comment by diogomart** [comment]
Sorry, I meant to ask if you tried PDBQT with ions with more than one atom in the PDBQT, and if so, are there any issues?

**Comment by diogomart** [comment]
Asking because @xrobin described his example as _minimal_

**Comment by xrobin** [comment]
@diogomart I meant minimal as in taken out of my bloated script.

But I can see ions got through, for instance the one with this SMILES worked fine: `C1COCC[NH+]1CCS(=O)(=O)[O-]`.

**Comment by jeeberhardt** [comment]
Fix is up now in the develop branch.
