### ISSUE TITLE
mk_prepare_ligand.py should return a non-0 exit code if it failed to create the output

### ISSUE THREAD

**Issue by xrobin** [forlilab/Meeko#64]
Running mk_prepare_ligand.py on some unsupported ligands like [Sr+2] fails. This is fine, however the script returns a success exit code (0) which makes it difficult to detect the failure.

```
echo "
     RDKit          3D

  1  0  0  0  0  0  0  0  0  0999 V2000
    0.0000    0.0000    0.0000 Sr  0  0  0  0  0 15  0  0  0  0  0  0
M  CHG  1   1   2
M  END
$$$$
" > test.sdf
mk_prepare_ligand.py -i test.sdf -o test.pdbqt
```
The script fails and prints the following output:
```
[16:04:31] Warning: molecule is tagged as 3D, but all Z coords are zero
[16:04:31] ERROR: Problems encountered parsing data fields
[16:04:31] ERROR: moving to the beginning of the next molecule
atom number 0 has None type, mol name: 

```
However it returns a status code of 0 which makes it difficult to detect that something failed:
```
echo $?
0

```
It would be very nice if mk_prepare_ligand.py could return a non-0 exit code to indicate a failure occurred.

**Comment by rwxayheee** [comment]
```
[16:04:31] Warning: molecule is tagged as 3D, but all Z coords are zero
[16:04:31] ERROR: Problems encountered parsing data fields
[16:04:31] ERROR: moving to the beginning of the next molecule
```
These are RDKit warnings or errors that may not immediately abort the execution (of reading a potentially multi-mol SDF) and do not necessarily lead to a failure to generate the PDBQT file. 

```
atom number 0 has None type, mol name: 
```
The above came from an unsuccessful attempt of PDBQTWriterLegacy.write_string. There's no immediate exit either, but the encounters are logged. 

It's understood that assignment of status code can be important, if there're external programs that depend on the exit code of mk_prepare_ligand.py. Proposed change: https://github.com/rwxayheee/Meeko/commit/7dcb9b111d5cd73adc0d59f4e64ddccab58669aa
```py
    # Determine if exit code should be non-zero based on processing results
    if output.num_files_written == 0:
        print("No PDBQT files were written due to errors!")
        sys.exit(1)  # full failure
    elif input_mol_with_failure > 0:
        print("Some molecules encountered errors!")
        sys.exit(2)  # partial failure
```

**Comment by diogomart** [comment]
@rwxayheee 7dcb9b111d5cd73adc0d59f4e64ddccab58669aa looks good, but I'd return 3 or any other number except the ones that have a defined meaning, see e.g.: https://www.geeksforgeeks.org/how-to-use-exit-code-to-read-from-terminal-from-script-and-with-logical-operators/

**Comment by rwxayheee** [comment]
Hi @diogomart 
Thank you for the suggestion. I will return exit codes that are neither 1 or 2 for the full/partial failure

**Comment by rwxayheee** [comment]
closing with #187
