### ISSUE TITLE
"ReadMOLFile-Error: bad atom count" error when open exported .sdf file in PyMOL

### ISSUE THREAD

**Issue by Le-Phung-Hien** [forlilab/Meeko#68]
Hi,

I have converted a vina results file to .sdf file using Meeko 0.5.0.
[capsaicin_out.pdbqt.txt](https://github.com/forlilab/Meeko/files/12502134/capsaicin_out.pdbqt.txt)
[capsaicin_out.sdf.txt](https://github.com/forlilab/Meeko/files/12502137/capsaicin_out.sdf.txt)

When open the sdf file in PyMOL 2.5.5, I have a "ReadMOLFile-Error: bad atom count" error. It happen with every file exported by Meeko. At first glance, the molecules can still be displayed and processed as normal in PyMOL.

I just wonder what can cause this error?

Thanks!

**Comment by rwxayheee** [comment]
Hi @Le-Phung-Hien 
Could you try removing the newlines at the end of sdf file? That fixed the "ReadMOLFile-Error: bad atom count" for me

**Comment by diogomart** [comment]
Fixed in aeffc06ff90771f62c4d169566a2743ea6c3b34f
Thank you @Le-Phung-Hien for reporting and @rwxayheee for finding the problem!

**Comment by Le-Phung-Hien** [comment]
@rwxayheee @diogomart Thanks a lot!
