### ISSUE TITLE
Create PDBQT receptor file from protonated PDB file.

### ISSUE THREAD

**Issue by Le-Phung-Hien** [forlilab/Meeko#69]
Hi,

Thanks for your great works!

Can I ask is it possible to use mk_prepare_receptor.py to make receptor file for Autodock? I used another program to protonate and assign charges to the receptor protein and exported as PDB file so I am not sure if the charges will be properly assigned to the PDBQT file.

**Comment by diogomart** [comment]
Hi,

Yes, see here: https://github.com/forlilab/Meeko#reactive-docking

At the moment it works only for standard amino acids and requires Amber atom names.

**Comment by Le-Phung-Hien** [comment]
Thanks!
