### ISSUE TITLE
PDBQT tree error (rigid amidine)

### ISSUE THREAD

**Issue by gkxiao** [forlilab/Meeko#7]
- [x] I believe this to be a bug with Meeko resulting from <a href="https://github.com/openbabel/openbabel/issues/2433">OpenBabel issue #2433</a>. I report it here because Meeko has the same error. 

## Environment Information
Operating system and version: Centos 7.4

## Expected Behavior
<img src="http://blog.molcalx.com.cn/wp-content/uploads/2020/11/2021101823531556.png">
<p style="text-align:center;">Example 1. C1(NC2=NC(C3=CN=CC=C3)=CC=N2)=CC=CC=C1</p>
<p>As for example 1 molecule, obabel give a PDBQT file with 2 rotatable bond instead of 3. The correct one looks like as following:</p>
<pre line="1">
REMARK  Name = EX1
REMARK  3 active torsions:
REMARK  status: ('A' for Active; 'I' for Inactive)
REMARK    1  A    between atoms: _1  and  _2
REMARK    2  A    between atoms: _2  and  _3
REMARK    3  A    between atoms: _5  and  _6
ROOT
ATOM      1  C1  UNL     1       3.354   0.587   0.763  0.00  0.00     0.041 A
ATOM     15  C11 UNL     1       4.730   0.740   0.977  0.00  0.00    -0.039 A
ATOM     16  C12 UNL     1       5.237   1.885   1.596  0.00  0.00    -0.060 A
ATOM     17  C13 UNL     1       4.371   2.898   1.998  0.00  0.00    -0.062 A
ATOM     18  C14 UNL     1       3.003   2.773   1.764  0.00  0.00    -0.060 A
ATOM     19  C15 UNL     1       2.501   1.632   1.133  0.00  0.00    -0.039 A
ENDROOT
BRANCH 1 2
ATOM      2  N1  UNL     1       2.812  -0.545   0.129  0.00  0.00    -0.324 N
ATOM     20  H1  UNL     1       2.532  -0.383  -0.830  0.00  0.00     0.170 HD
BRANCH 2 3
ATOM      3  C2  UNL     1       3.296  -1.851   0.224  0.00  0.00     0.227 A
ATOM      4  N2  UNL     1       3.942  -2.233   1.334  0.00  0.00    -0.213 NA
ATOM      5  C3  UNL     1       4.393  -3.501   1.427  0.00  0.00     0.077 A
ATOM     12  C9  UNL     1       4.180  -4.407   0.410  0.00  0.00    -0.017 A
ATOM     13  C10 UNL     1       3.504  -3.933  -0.691  0.00  0.00     0.033 A
ATOM     14  N4  UNL     1       3.060  -2.669  -0.809  0.00  0.00    -0.221 NA
BRANCH 5 6
ATOM      6  C4  UNL     1       5.110  -3.815   2.675  0.00  0.00     0.019 A
ATOM      7  C5  UNL     1       6.100  -4.795   2.757  0.00  0.00     0.036 A
ATOM      8  N3  UNL     1       6.792  -5.119   3.879  0.00  0.00    -0.264 NA
ATOM      9  C6  UNL     1       6.496  -4.421   4.994  0.00  0.00     0.027 A
ATOM     10  C7  UNL     1       5.546  -3.417   5.038  0.00  0.00    -0.043 A
ATOM     11  C8  UNL     1       4.853  -3.116   3.866  0.00  0.00    -0.050 A
ENDBRANCH 5 6
ENDBRANCH 2 3
ENDBRANCH 1 2
TORSDOF 3
</pre>

## Actual Behavior
<p>The torsions in PDBQT file did not include bond C_2-N_3. This will result in docking failure. Let me show you an redocking failure: <a href="https://github.com/gkxiao/openbabel_2433">openbabel_2433</a></p>

## Steps to Reproduce

<pre line="1">
(base) [gkxiao@master demo]$ cat ex1.smi
C1(NC2=NC(C3=CN=CC=C3)=CC=N2)=CC=CC=C1 EX01
(base) [gkxiao@master demo]$ obabel -ismi ex1.smi -opdbqt --gen3d --best
REMARK  Name = EX01
REMARK  2 active torsions:
REMARK  status: ('A' for Active; 'I' for Inactive)
REMARK    1  A    between atoms: C_1  and  N_2
REMARK    2  A    between atoms: C_5  and  C_6
REMARK                            x       y       z     vdW  Elec       q    Type
REMARK                         _______ _______ _______ _____ _____    ______ ____
ROOT
ATOM      1  N   UNL     1       2.812  -0.545   0.128  0.00  0.00    +0.000 N
ATOM      2  C   UNL     1       3.296  -1.851   0.224  0.00  0.00    +0.000 A
ATOM      3  N   UNL     1       3.942  -2.233   1.334  0.00  0.00    +0.000 NA
ATOM      4  C   UNL     1       4.393  -3.501   1.427  0.00  0.00    +0.000 A
ATOM      5  C   UNL     1       4.180  -4.407   0.410  0.00  0.00    +0.000 A
ATOM      6  C   UNL     1       3.504  -3.932  -0.691  0.00  0.00    +0.000 A
ATOM      7  N   UNL     1       3.060  -2.669  -0.809  0.00  0.00    +0.000 NA
ATOM      8  H   UNL     1       2.532  -0.383  -0.830  0.00  0.00    +0.000 HD
ENDROOT
BRANCH   1   9
ATOM      9  C   UNL     1       3.354   0.587   0.763  0.00  0.00    +0.000 A
ATOM     10  C   UNL     1       4.730   0.740   0.977  0.00  0.00    +0.000 A
ATOM     11  C   UNL     1       5.237   1.885   1.596  0.00  0.00    +0.000 A
ATOM     12  C   UNL     1       4.371   2.898   1.998  0.00  0.00    +0.000 A
ATOM     13  C   UNL     1       3.003   2.773   1.765  0.00  0.00    +0.000 A
ATOM     14  C   UNL     1       2.501   1.632   1.133  0.00  0.00    +0.000 A
ENDBRANCH   1   9
BRANCH   4  15
ATOM     15  C   UNL     1       5.110  -3.815   2.675  0.00  0.00    +0.000 A
ATOM     16  C   UNL     1       6.100  -4.795   2.757  0.00  0.00    +0.000 A
ATOM     17  N   UNL     1       6.791  -5.119   3.879  0.00  0.00    +0.000 NA
ATOM     18  C   UNL     1       6.496  -4.421   4.994  0.00  0.00    +0.000 A
ATOM     19  C   UNL     1       5.546  -3.417   5.038  0.00  0.00    +0.000 A
ATOM     20  C   UNL     1       4.853  -3.116   3.867  0.00  0.00    +0.000 A
ENDBRANCH   4  15
TORSDOF 2
</pre>

**Comment by diogomart** [comment]
Thanks for reporting! We are aiming to fix this in the next release.

**Comment by diogomart** [comment]
Fixed in 7e2574838a4ed38984dcd41878b236485477af22, will release v0.3.0 soon
