### ISSUE TITLE
'G' atom in pdbqt

### ISSUE THREAD

**Issue by lh12565** [forlilab/Meeko#70]
Hi, I use meeko to convert sdf to pdbqt. The pdbqt file (lig_out.pdbqt) and the result of vina 1.2.3 have 'G' atoms. I save complex of the target protein 'pro.pdbqt' and the ligand 'lig_out.pdbqt' to 'complex.pdb' via pymol, then I import the 'complex.pdb' to maestro. There is an error as below:
```
WARNING mmpdb_build_altloc_db_for_atom: Atom records 1030 and 1051 in residue 1 (UNL ), chain ' ' have same name ' C  '
WARNING mmpdb_build_altloc_db_for_atom: Atom records 1030 and 1052 in residue 1 (UNL ), chain ' ' have same name ' C  '
FATAL mmpdb_atom_push_back: no recognizable element could be derived
                      from PDB atom #1053 (G  ), residue 1 (UNL )
FATAL mmpdb_read: mmpdb_atom_push_back failed
Check atom names to see if element types can be determined.
```
I don't know what the 'G' atom represents? How to successfully import to other software? Thanks!

**Comment by diogomart** [comment]
Hi,
The Gn/CGn atoms are for restoring bonds within macrocycle rings that have been removed to allow sampling macrocycle conformers.

Use mk_export.py on the vina output to convert to SDF, which is a better format than pdbqt.

**Comment by lh12565** [comment]
> Hi, The Gn/CGn atoms are for restoring bonds within macrocycle rings that have been removed to allow sampling macrocycle conformers.
> 
> Use mk_export.py on the vina output to convert to SDF, which is a better format than pdbqt.

Thanks! I have one more question. I use a library (~250000) to screen molecules. I prepared the molecules by obabel and meeko, and then to screen respectively. I found no intersection in the top 100 molecules of their results. Is this result normal? How should I choose this result? Thanks!

**Comment by diogomart** [comment]
Which Vina version? v1.2.3 was scoring molecules with CGn/Gn atoms much more favorably.

**Comment by lh12565** [comment]
> Which Vina version? v1.2.3 was scoring molecules with CGn/Gn atoms much more favorably.

I used v1.2.3 for both. The structure produced by obabel did not have CGn/Gn atoms.

**Comment by diogomart** [comment]
I suspect that the top 100 from meeko are macrocycles, due to the bug in v1.2.3. See https://github.com/ccsb-scripps/AutoDock-Vina/issues/200

**Comment by lh12565** [comment]
> I suspect that the top 100 from meeko are macrocycles, due to the bug in v1.2.3. See [ccsb-scripps/AutoDock-Vina#200](https://github.com/ccsb-scripps/AutoDock-Vina/issues/200)

So, should I update vina to version 1.2.5 to avoid this bug?

**Comment by diogomart** [comment]
Yes
