### ISSUE TITLE
ATOM syntax incorrect: "CG0" is not a valid AutoDock type.

### ISSUE THREAD

**Issue by Le-Phung-Hien** [forlilab/Meeko#71]
Hi, 

I'm running AutoDock Vina 1.1.2 using Meeko-generated ligands. One ligand cause the error "ATOM syntax incorrect: "CG0" is not a valid AutoDock type."

This is the PDBQT file: 
[PQK4F-1.pdbqt.txt](https://github.com/ccsb-scripps/AutoDock-Vina/files/12524283/PQK4F-1.pdbqt.txt)

And this is the ligand generated by openbabel:
[PQK4F-2_op.pdbqt.txt](https://github.com/ccsb-scripps/AutoDock-Vina/files/12524307/PQK4F-2_op.pdbqt.txt)

Is there any way to get around this error?

Thanks!

**Comment by diogomart** [comment]
Hi,

You need vina 1.2.5 to handle those atom types, which are specific for macrocycle sampling. If you want to use vina 1.1.2 you can disable macrocycle sampling in meeko with option `--rigid_macrocycles`.

**Comment by vincrichard** [comment]
Hello @diogomart,
Thank you for your awesome work on this project and AutoDock-Vina.
I am having the same issue as Le-Phung-Hien, but I do have vina 1.2.5. Adding --rigid_macrocycles do fix it. 
Wondering if there could be any other cause?

```
/opt/elix/vina/vina --help
AutoDock Vina v1.2.5
[...]
/tmp# wget https://github.com/ccsb-scripps/AutoDock-Vina/releases/download/v1.2.5/vina_1.2.5_linux_x86_64
[...]
/tmp# md5sum vina_1.2.5_linux_x86_64 /opt/elix/vina/vina_1.2.5_linux_x86_64 
a1a5d276535db56db71f94f403b8939e  vina_1.2.5_linux_x86_64
a1a5d276535db56db71f94f403b8939e  /opt/elix/vina/vina_1.2.5_linux_x86_64
```

**Comment by diogomart** [comment]
@vincrichard 1.2.5 recognizes CG0. Can you share the input files and command line call that reproduces the issue and can you share also the full error message?

**Comment by vincrichard** [comment]
@diogomart Sorry, you are right. It does work as intended. I was working with Vina GPU and expected the same functionality since my vina version was 1.2.5. I will investigate over there. Thank you.
