### ISSUE TITLE
Different charges than prepare_ligand4.py

### ISSUE THREAD

**Issue by echen1214** [forlilab/Meeko#74]
Hi,

I have found the meeko package to be quite useful, thank you for developing this.

However, I have noticed the assigned partial charges are slightly different between Meeko 0.5 and MGLtools 1.5.6 prepare_ligand4.py. Is this the intended performance? Am I missing something here that explains the discrepancy? See the attached files from the ligand of 1e66. 

These two files were generated using the following commands:
`pythonsh prepare_ligand4.py -l 1e66_ligand.mol2 -o 1e66_ligand.mgl.nphs.pdbqt -U nphs`
and
`mk_prepare_ligand.py -l 1e66_ligand.mol2 -o 1e66_ligand.pdbqt -multimol_outdir ./`
`mv 1e66_ligand.pdbqt 1e66_ligand.mk.pdbqt`

Regards,
Eric

[mk_test.tgz](https://github.com/forlilab/Meeko/files/13218361/mk_test.tgz)

**Comment by diogomart** [comment]
Hi, the partial charges in meeko come from the Gasteiger impementation in RDKit, while those from `prepare_ligand4` come from the Gasteiger implementation in MGLTools (which may be the same as in OpenBabel, I don't know). So yes, there could be differences, but generally the agreement is excellent. In the example you sent, differences are within 0.01 charge units, which is OK.

**Comment by echen1214** [comment]
Thanks for the clarification!
