### ISSUE TITLE
mk_prepare_receptor

### ISSUE THREAD

**Issue by TommyBiomodellingAU** [forlilab/Meeko#77]
Is it not possible to use mk_prepare_receptor to prepare a pdb file for flexible docking only and not for reactive docking?

**Comment by diogomart** [comment]
Yes, use `-f` or  `--flexres` instead of `--reactive_flexres`.

**Comment by TommyBiomodellingAU** [comment]
right, thanks. The actual problem seems to be that mk_prepare_receptor.py does not recognize the terminals of the pdb structures i am using. It just says "amino acid does not match template". It happens with and without ACE/NMA capping as well

**Comment by diogomart** [comment]
Currently it expect all atom names, including hydrogens, to match the atom names from Amber, and only standard amino acids are supported. So it is very restrictive. The new version that fixes these issues will be released in a few weeks.

**Comment by diogomart** [comment]
Closing issue: as of current develop branch all standard residues should work whether their termination is charged, neutral, or capped with ACE/NME. Feature will be released in v0.6.0 soon.
