### ISSUE TITLE
Create PDBQT file instead of string

### ISSUE THREAD

**Issue by daoquangtung2411** [forlilab/Meeko#80]
Hi Diogo,

Thank you for your application.

I have a question regarding ligand preparation. I'm currently use meeko 0.5.0 for ligand preparation for docking. And I wonder if I can write PDBQT file instead of PDBQT string (in PDBQTWriterLegacy)

Thank you in advanced!

**Comment by diogomart** [comment]
Not directly from PDBQTWriterLegacy, you have to use the standard Python functions to write the string to a file: https://docs.python.org/3/tutorial/inputoutput.html#reading-and-writing-files

**Comment by daoquangtung2411** [comment]
Thank you very much for your instant support.
