### ISSUE TITLE
Differences from tools provided in ADFRsuite

### ISSUE THREAD

**Issue by eunos-1128** [forlilab/Meeko#88]
Hello,

meeko has `mk_prepare_receptor.py` and `mk_prepare_ligand.py`, while ADFRsuite has similar tools called `prepare_receptor` and `prepare_ligand`.

Where can I find a detailed description of the differences between these command line tools?

I tried to look into but could not find it.

If these tools are basically same, is it ok to assume that they do same things on running without options? 

Since, I've found that `mk_prepare_ligand.py` and `prepare_ligand` result in different outputs respectively when running each command without options. 

I would appreciate it if you could tell me.

**Comment by rwxayheee** [comment]
hi @eunos-1128 

> Since, I've found that mk_prepare_ligand.py and prepare_ligand result in different outputs respectively when running each command without options.

Yes, the layouts are a lot different. But content-wise the difference may or may not be important to your projects. 

Meeko prepares ligand PDBQT with possibly useful additional information, such as Smiles mapping and atom-typing to support macrocycle sampling (enabled by default). 

Also, prepare_receptor and prepare_ligand in ADFRsuite perceive atom types using geometry and can tolerate not very clear valence/topology information and missing hydrogens. There might be other differences. If you notice any other differences or have any concerns, feel free to comment

**Comment by diogomart** [comment]
In addition, meeko uses rdkit, and rdkit performs sanity checks on the valence and other properties to make sure the molecules are reasonable.
