### ISSUE TITLE
Meeko fails to recognize `A` atom type from PDBQT

### ISSUE THREAD

**Issue by althea-hansel** [forlilab/Meeko#93]
When passing in a PDBQT receptor for `mk_prepare_receptor.py`, the following error is raised from RDKit:

```
****
Post-condition Violation
Element 'A' not found
Violation occurred on line 93 in file /project/build/temp.linux-x86_64-cpython-311/rdkit/Code/GraphMol/PeriodicTable.h
Failed Expression: anum > -1
****
```

I have encountered this before, since RDKit cannot recognize the `A` atom type.

**Comment by diogomart** [comment]
Maybe we shouldn't support PDBQT as input. Can you find a workaround or do you absolutely need this feature?

**Comment by althea-hansel** [comment]
I have always manually converted between the AD atom types and elements, I forget if the method used to live in Meeko or Ringtail or not. I think functionally it doesn't make a difference if we drop the feature (it is easy to convert in pymol, etc). We would just need to update the command-line help

**Comment by diogomart** [comment]
Thanks, I'll update command line help then.
