### ISSUE TITLE
Preserving original charges when converting MOL2 to PDBQT

### ISSUE THREAD

**Issue by vwcruzeiro** [forlilab/Meeko#98]
Dear Development Team,

I am currently working with a ligand in **MOL2 format** and utilizing the `mk_prepare_ligand.py` script to convert it into **PDBQT format**. I have encountered an issue where the script does not retain the original charges specified within the MOL2 file; instead, it assigns new charges during the conversion process.

Would it be possible to modify the script or use a parameter that instructs it to preserve the original charges from the MOL2 file? Your assistance in resolving this matter would be greatly appreciated.

Thank you for your support and dedication.

**Comment by diogomart** [comment]
That should be possible, we'll look into it as this sounds particularly useful. However, meeko relies on RDKit, and [RDKit doesn't like all flavors of MOL2](https://github.com/forlilab/meeko?tab=readme-ov-file#usage-notes). Would you be comfortable carrying the charges using SDF? I thinkt RDKit and OpenFF developers agreed on a spec that uses atom or molecule properties. Asking because not supporting MOL2 at all has crossed my mind.

**Comment by rwxayheee** [comment]
Hi @vwcruzeiro 
This seems to be a known issue with RDKit according to the [Usage Notes in README](https://github.com/forlilab/Meeko/blob/develop/README.md#usage-notes). You can still process a ligand from MOL2 format but will need to manually assign the formal charge. In addition to the posts mentioned, [this discussion](https://sourceforge.net/p/rdkit/mailman/message/35989934/) might be helpful with [an example by the RDKit dev](https://gist.github.com/greglandrum/7f546d1e35c2df537c68a64d887793b8). After you assign the formal charges you should be able to generate the PDBQT following the guidance from [here](https://github.com/forlilab/Meeko/?tab=readme-ov-file#api-changes-in-v05) for your `rdkit_molecule_3D_with_Hs`

**Comment by diogomart** [comment]
Added in 926f409637f6c6d61e97578656907ce44666e45e, use `--charge_model from_mol2`. You'll need to clone the repo and [install locally](926f409).

**Comment by vwcruzeiro** [comment]
@diogomart , I cannot thank you enough for including this functionality so quickly! I tested it and it seems to be working.
